import { useState } from "react";
import { Plus, RotateCcw, Save, Trash2 } from "lucide-react";

const DEFAULT_SETTINGS = {
  businessName: "Overkill Solutions",
  defaultTaxPercent: 7,
  defaultDepositPercent: 40,
  invoiceFooter:
    "Generated by Overkill Solutions Internal Production System",

  customerFields: {
    requireName: true,
    requirePhone: true,
    requireEmail: false,
    showAddress: true,
  },

  machineRates: {
    p1s: 3,
    x1c: 3,
    h2sPrint: 3,
    h2sLaser10w: 4,
    h2sLaser40w: 6,
    h2sCutter: 4,
  },

  machineModules: [
    { id: "p1s", label: "Bambu P1S", type: "printer", rateKey: "p1s", active: true },
    { id: "x1c", label: "Bambu X1C", type: "printer", rateKey: "x1c", active: true },
    { id: "h2s", label: "Bambu H2S", type: "printer", rateKey: "h2sPrint", active: true },
    { id: "h2s-laser-10w", label: "H2S Laser — 10W", type: "laser", rateKey: "h2sLaser10w", active: true },
    { id: "h2s-laser-40w", label: "H2S Laser — 40W", type: "laser", rateKey: "h2sLaser40w", active: true },
    { id: "h2s-cutter", label: "H2S Cutter", type: "cutter", rateKey: "h2sCutter", active: true },
  ],

  nozzles: [
    { id: "0.2", label: "0.2mm — Detail", diameter: 0.2, machineRateAdd: 1, marketMultiplier: 1.25, active: true },
    { id: "0.4", label: "0.4mm — Standard", diameter: 0.4, machineRateAdd: 0, marketMultiplier: 1, active: true },
    { id: "0.6", label: "0.6mm — Strong/Faster", diameter: 0.6, machineRateAdd: 0.25, marketMultiplier: 1.05, active: true },
    { id: "0.8", label: "0.8mm — Heavy Duty", diameter: 0.8, machineRateAdd: 0.5, marketMultiplier: 1.1, active: true },
  ],

  cadPresets: [
    { id: "basic", label: "Basic CAD", amount: 25, active: true },
    { id: "standard", label: "Standard CAD", amount: 45, active: true },
    { id: "advanced", label: "Advanced CAD", amount: 70, active: true },
    { id: "complex", label: "Complex CAD", amount: 110, active: true },
    { id: "engineering", label: "Engineering CAD", amount: 175, active: true },
    { id: "custom", label: "Custom Quote", amount: 0, active: true },
  ],

  setupFees: {
    basic: 5,
    moderate: 15,
    advanced: 30,
  },

  integrationCharges: {
    none: 0,
    simple: 15,
    moderate: 30,
    advanced: 50,
    complex: 75,
  },

  minimumCharges: {
    basicProjectMinimum: 25,
    printMinimum: 25,
    cadPrintMinimum: 60,
    engravingMinimum: 20,
    vinylMinimum: 20,
    customMinimum: 40,
  },

  bufferCurve: {
    under50: 20,
    under100: 15,
    under200: 12,
    under400: 10,
    over400: 8,
  },

  printMaterials: [
    { id: "pla", label: "PLA", costPerGram: 0.03, group: "standard", active: true },
    { id: "petg", label: "PETG", costPerGram: 0.03, group: "standard", active: true },
    { id: "abs", label: "ABS", costPerGram: 0.03, group: "standard", active: true },
    { id: "asa", label: "ASA", costPerGram: 0.05, group: "specialty", active: true },
    { id: "tpu", label: "TPU", costPerGram: 0.05, group: "specialty", active: true },
    { id: "pc", label: "PC", costPerGram: 0.06, group: "specialty", active: true },
    { id: "carbon-fiber", label: "Carbon Fiber", costPerGram: 0.07, group: "specialty", active: true },
  ],

  engravingMaterials: [
    { id: "none", label: "None / Customer Provided", packCost: 0, packCount: 1, colors: "N/A", materialType: "customer-provided", active: true },
    { id: "aluminum-card", label: "Aluminum Card", packCost: 3.89, packCount: 1, colors: "Black, Silver, Red, Blue, Gold, Rainbow", materialType: "metal", active: true },
    { id: "stainless-steel", label: "Stainless Steel", packCost: 0, packCount: 1, colors: "Raw Stainless", materialType: "metal", active: true },
    { id: "titanium", label: "Titanium", packCost: 0, packCount: 1, colors: "Raw Titanium", materialType: "metal", active: true },
    { id: "basswood-2mm", label: "2mm Basswood Plywood", packCost: 13.89, packCount: 6, colors: "Natural", materialType: "wood", active: true },
    { id: "basswood-3mm", label: "3mm Basswood Plywood", packCost: 14.89, packCount: 6, colors: "Natural", materialType: "wood", active: true },
    { id: "acrylic-opaque-glossy", label: "3mm Opaque Glossy Acrylic", packCost: 17.89, packCount: 3, colors: "Black, Red, Orange, Yellow, Green", materialType: "acrylic", active: true },
  ],

  vinylMaterials: [
    { id: "none", label: "None / Customer Provided", packCost: 0, packCount: 1, colors: "N/A", active: true },
    { id: "matte-removable-vinyl", label: "Matte Removable Vinyl", packCost: 9.89, packCount: 10, colors: "Black, Red, Orange, Yellow, Green, Blue, Silver, White", active: true },
    { id: "carbon-fiber-removable-vinyl", label: "Carbon Fiber Textured Removable Vinyl", packCost: 9.89, packCount: 10, colors: "Black Carbon Fiber", active: true },
    { id: "printable-vinyl-paper", label: "White Matte Printable Vinyl Sticker Paper", packCost: 8.89, packCount: 25, colors: "White", active: true },
    { id: "transfer-tape", label: "Transfer Tape", packCost: 7.89, packCount: 10, colors: "Clear Grid", active: true },
    { id: "matte-heat-transfer-vinyl", label: "Matte Heat Transfer Vinyl", packCost: 10.89, packCount: 10, colors: "Black, Red, Pink, Orange, Yellow, Cream, Green, Blue, Gray, White", active: true },
  ],

  paymentMethods: ["Venmo", "Cash", "Cash App", "PayPal", "Zelle"],
};

function normalizeCadPresets(savedCadPresets) {
  if (Array.isArray(savedCadPresets)) return savedCadPresets;

  if (savedCadPresets && typeof savedCadPresets === "object") {
    return DEFAULT_SETTINGS.cadPresets.map((preset) => ({
      ...preset,
      amount: savedCadPresets[preset.id] ?? preset.amount,
    }));
  }

  return DEFAULT_SETTINGS.cadPresets;
}

function mergeSettings(saved) {
  return {
    ...DEFAULT_SETTINGS,
    ...saved,
    customerFields: { ...DEFAULT_SETTINGS.customerFields, ...(saved?.customerFields || {}) },
    machineRates: { ...DEFAULT_SETTINGS.machineRates, ...(saved?.machineRates || {}) },
    machineModules: saved?.machineModules || DEFAULT_SETTINGS.machineModules,
    nozzles: saved?.nozzles || DEFAULT_SETTINGS.nozzles,
    cadPresets: normalizeCadPresets(saved?.cadPresets),
    setupFees: { ...DEFAULT_SETTINGS.setupFees, ...(saved?.setupFees || {}) },
    integrationCharges: { ...DEFAULT_SETTINGS.integrationCharges, ...(saved?.integrationCharges || {}) },
    minimumCharges: { ...DEFAULT_SETTINGS.minimumCharges, ...(saved?.minimumCharges || {}) },
    bufferCurve: { ...DEFAULT_SETTINGS.bufferCurve, ...(saved?.bufferCurve || {}) },
    printMaterials: saved?.printMaterials || DEFAULT_SETTINGS.printMaterials,
    engravingMaterials: saved?.engravingMaterials || DEFAULT_SETTINGS.engravingMaterials,
    vinylMaterials: saved?.vinylMaterials || DEFAULT_SETTINGS.vinylMaterials,
    paymentMethods: saved?.paymentMethods || DEFAULT_SETTINGS.paymentMethods,
  };
}

function getInitialSettings() {
  try {
    const saved = localStorage.getItem("overkill_settings");
    return saved ? mergeSettings(JSON.parse(saved)) : DEFAULT_SETTINGS;
  } catch {
    return DEFAULT_SETTINGS;
  }
}

function makeId(label) {
  return String(label || "new-item")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function Field({ label, value, onChange, type = "number", step = "0.01" }) {
  return (
    <label className="field">
      <span>{label}</span>
      <input
        type={type}
        value={value}
        step={type === "number" ? step : undefined}
        onChange={(event) => onChange(event.target.value)}
      />
    </label>
  );
}

function MaterialHeader({ title, description, onAdd }) {
  return (
    <div className="page-heading-row material-section-heading">
      <div>
        <h3 className="card-title">{title}</h3>
        <p className="muted-text">{description}</p>
      </div>

      <button className="secondary-button" type="button" onClick={onAdd}>
        <Plus size={18} />
        Add
      </button>
    </div>
  );
}

export default function SettingsPage() {
  const [settings, setSettings] = useState(getInitialSettings);
  const [saveMessage, setSaveMessage] = useState("");

  function update(key, value) {
    setSettings((current) => ({
      ...current,
      [key]: value,
    }));
  }

  function updateNested(section, key, value) {
    setSettings((current) => ({
      ...current,
      [section]: {
        ...current[section],
        [key]: value,
      },
    }));
  }

  function updatePaymentMethods(value) {
    const methods = value
      .split("\n")
      .map((item) => item.trim())
      .filter(Boolean);

    update("paymentMethods", methods);
  }

  function updateArrayItem(section, itemId, key, value) {
    setSettings((current) => ({
      ...current,
      [section]: current[section].map((item) => {
        if (item.id !== itemId) return item;

        const nextItem = {
          ...item,
          [key]: value,
        };

        if (key === "label") {
          nextItem.id = makeId(value);
        }

        return nextItem;
      }),
    }));
  }

  function addArrayItem(section, template) {
    setSettings((current) => ({
      ...current,
      [section]: [...current[section], template],
    }));
  }

  function removeArrayItem(section, itemId, label = "item") {
    const confirmed = window.confirm(`Delete this ${label}?`);
    if (!confirmed) return;

    setSettings((current) => ({
      ...current,
      [section]: current[section].filter((item) => item.id !== itemId),
    }));
  }

  function addCadPreset() {
    addArrayItem("cadPresets", {
      id: `new-cad-tier-${Date.now()}`,
      label: "New CAD Tier",
      amount: 0,
      active: true,
    });
  }

  function addMachineModule() {
    addArrayItem("machineModules", {
      id: `new-module-${Date.now()}`,
      label: "New Machine / Module",
      type: "printer",
      rateKey: "p1s",
      active: true,
    });
  }

  function addNozzle() {
    addArrayItem("nozzles", {
      id: `new-nozzle-${Date.now()}`,
      label: "New Nozzle",
      diameter: 0.4,
      machineRateAdd: 0,
      marketMultiplier: 1,
      active: true,
    });
  }

  function addPrintMaterial() {
    addArrayItem("printMaterials", {
      id: `new-print-material-${Date.now()}`,
      label: "New Print Material",
      costPerGram: 0.03,
      group: "standard",
      active: true,
    });
  }

  function addSheetMaterial(section) {
    addArrayItem(section, {
      id: `new-sheet-material-${Date.now()}`,
      label: "New Material",
      packCost: 0,
      packCount: 1,
      colors: "Black, White",
      materialType: "custom",
      active: true,
    });
  }

  function saveSettings() {
    localStorage.setItem("overkill_settings", JSON.stringify(settings));
    setSaveMessage("Settings saved locally.");
  }

  function resetSettings() {
    const confirmed = window.confirm(
      "Reset settings back to Overkill defaults? This will also reset material/module/nozzle lists."
    );

    if (!confirmed) return;

    setSettings(DEFAULT_SETTINGS);
    localStorage.setItem("overkill_settings", JSON.stringify(DEFAULT_SETTINGS));
    setSaveMessage("Settings reset to defaults.");
  }

  return (
    <section className="page-panel">
      <div className="page-heading-row">
        <div>
          <h2 className="section-title brand-font">Settings</h2>
          <p className="muted-text">
            Persistent defaults for customer info, rates, modules, nozzles, materials, CAD tiers, minimums, and PDFs.
          </p>

          {saveMessage && <p className="helper-note">{saveMessage}</p>}
        </div>

        <div className="settings-action-row">
          <button className="secondary-button" onClick={resetSettings}>
            <RotateCcw size={18} />
            Reset
          </button>

          <button className="primary-button settings-save-button" onClick={saveSettings}>
            <Save size={18} />
            Save Settings
          </button>
        </div>
      </div>

      <div className="settings-grid">
        <div className="form-card">
          <h3 className="card-title">Business Defaults</h3>

          <div className="form-grid">
            <Field label="Business Name" type="text" value={settings.businessName} onChange={(value) => update("businessName", value)} />
            <Field label="Default Tax %" value={settings.defaultTaxPercent} onChange={(value) => update("defaultTaxPercent", value)} />
            <Field label="Default Deposit %" value={settings.defaultDepositPercent} onChange={(value) => update("defaultDepositPercent", value)} />
          </div>

          <label className="field single-row-gap">
            <span>Invoice / PDF Footer Text</span>
            <textarea value={settings.invoiceFooter} onChange={(event) => update("invoiceFooter", event.target.value)} />
          </label>
        </div>

        <div className="form-card">
          <h3 className="card-title">Customer Fields</h3>

          <div className="settings-checkbox-list">
            {[
              ["requireName", "Require customer name"],
              ["requirePhone", "Require phone number"],
              ["requireEmail", "Require email address"],
              ["showAddress", "Show address field for shipping / delivery"],
            ].map(([key, label]) => (
              <label className="aspect-option" key={key}>
                <input
                  type="checkbox"
                  checked={Boolean(settings.customerFields[key])}
                  onChange={(event) =>
                    updateNested("customerFields", key, event.target.checked)
                  }
                />
                <span>{label}</span>
              </label>
            ))}
          </div>
        </div>

        <div className="form-card">
          <h3 className="card-title">Machine Rates</h3>

          <div className="form-grid">
            <Field label="P1S Print Rate ($/hr)" value={settings.machineRates.p1s} onChange={(value) => updateNested("machineRates", "p1s", value)} />
            <Field label="X1C Print Rate ($/hr)" value={settings.machineRates.x1c} onChange={(value) => updateNested("machineRates", "x1c", value)} />
            <Field label="H2S Print Rate ($/hr)" value={settings.machineRates.h2sPrint} onChange={(value) => updateNested("machineRates", "h2sPrint", value)} />
            <Field label="H2S 10W Laser Rate ($/hr)" value={settings.machineRates.h2sLaser10w} onChange={(value) => updateNested("machineRates", "h2sLaser10w", value)} />
            <Field label="H2S 40W Laser Rate ($/hr)" value={settings.machineRates.h2sLaser40w} onChange={(value) => updateNested("machineRates", "h2sLaser40w", value)} />
            <Field label="H2S Cutter Rate ($/hr)" value={settings.machineRates.h2sCutter} onChange={(value) => updateNested("machineRates", "h2sCutter", value)} />
          </div>
        </div>

        <div className="form-card">
          <h3 className="card-title">Setup Fees</h3>

          <div className="form-grid">
            <Field label="Basic Setup" value={settings.setupFees.basic} onChange={(value) => updateNested("setupFees", "basic", value)} />
            <Field label="Moderate Setup" value={settings.setupFees.moderate} onChange={(value) => updateNested("setupFees", "moderate", value)} />
            <Field label="Advanced Setup" value={settings.setupFees.advanced} onChange={(value) => updateNested("setupFees", "advanced", value)} />
          </div>
        </div>

        <div className="form-card">
          <h3 className="card-title">Project Integration Charges</h3>

          <div className="form-grid">
            <Field label="No Integration" value={settings.integrationCharges.none} onChange={(value) => updateNested("integrationCharges", "none", value)} />
            <Field label="Simple Integration" value={settings.integrationCharges.simple} onChange={(value) => updateNested("integrationCharges", "simple", value)} />
            <Field label="Moderate Integration" value={settings.integrationCharges.moderate} onChange={(value) => updateNested("integrationCharges", "moderate", value)} />
            <Field label="Advanced Integration" value={settings.integrationCharges.advanced} onChange={(value) => updateNested("integrationCharges", "advanced", value)} />
            <Field label="Complex Integration" value={settings.integrationCharges.complex} onChange={(value) => updateNested("integrationCharges", "complex", value)} />
          </div>
        </div>

        <div className="form-card">
          <h3 className="card-title">Minimum Charges</h3>

          <div className="form-grid">
            <Field label="Basic Project Minimum" value={settings.minimumCharges.basicProjectMinimum} onChange={(value) => updateNested("minimumCharges", "basicProjectMinimum", value)} />
            <Field label="Print Minimum" value={settings.minimumCharges.printMinimum} onChange={(value) => updateNested("minimumCharges", "printMinimum", value)} />
            <Field label="CAD + Print Minimum" value={settings.minimumCharges.cadPrintMinimum} onChange={(value) => updateNested("minimumCharges", "cadPrintMinimum", value)} />
            <Field label="Engraving Minimum" value={settings.minimumCharges.engravingMinimum} onChange={(value) => updateNested("minimumCharges", "engravingMinimum", value)} />
            <Field label="Vinyl Minimum" value={settings.minimumCharges.vinylMinimum} onChange={(value) => updateNested("minimumCharges", "vinylMinimum", value)} />
            <Field label="Custom Fabrication Minimum" value={settings.minimumCharges.customMinimum} onChange={(value) => updateNested("minimumCharges", "customMinimum", value)} />
          </div>
        </div>

        <div className="form-card">
          <h3 className="card-title">Buffer Curve</h3>

          <div className="form-grid">
            <Field label="$0–50 Buffer %" value={settings.bufferCurve.under50} onChange={(value) => updateNested("bufferCurve", "under50", value)} />
            <Field label="$50–100 Buffer %" value={settings.bufferCurve.under100} onChange={(value) => updateNested("bufferCurve", "under100", value)} />
            <Field label="$100–200 Buffer %" value={settings.bufferCurve.under200} onChange={(value) => updateNested("bufferCurve", "under200", value)} />
            <Field label="$200–400 Buffer %" value={settings.bufferCurve.under400} onChange={(value) => updateNested("bufferCurve", "under400", value)} />
            <Field label="$400+ Buffer %" value={settings.bufferCurve.over400} onChange={(value) => updateNested("bufferCurve", "over400", value)} />
          </div>
        </div>

        <div className="form-card">
          <h3 className="card-title">Payment Methods</h3>

          <label className="field">
            <span>One payment method per line</span>
            <textarea value={settings.paymentMethods.join("\n")} onChange={(event) => updatePaymentMethods(event.target.value)} />
          </label>
        </div>

        <div className="form-card full-span">
          <MaterialHeader
            title="Machine Modules"
            description="Control which printers, lasers, and cutter modules appear in the calculator and production logs."
            onAdd={addMachineModule}
          />

          <div className="material-settings-list">
            {settings.machineModules.map((module) => (
              <div className="material-settings-row" key={module.id}>
                <div className="form-grid material-settings-grid">
                  <Field label="Module Name" type="text" value={module.label} onChange={(value) => updateArrayItem("machineModules", module.id, "label", value)} />

                  <label className="field">
                    <span>Module Type</span>
                    <select value={module.type} onChange={(event) => updateArrayItem("machineModules", module.id, "type", event.target.value)}>
                      <option value="printer">Printer</option>
                      <option value="laser">Laser</option>
                      <option value="cutter">Cutter</option>
                      <option value="other">Other</option>
                    </select>
                  </label>

                  <label className="field">
                    <span>Rate Key</span>
                    <select value={module.rateKey} onChange={(event) => updateArrayItem("machineModules", module.id, "rateKey", event.target.value)}>
                      {Object.keys(settings.machineRates).map((rateKey) => (
                        <option key={rateKey} value={rateKey}>{rateKey}</option>
                      ))}
                    </select>
                  </label>

                  <label className="field checkbox-field material-active-field">
                    <input type="checkbox" checked={Boolean(module.active)} onChange={(event) => updateArrayItem("machineModules", module.id, "active", event.target.checked)} />
                    <span>Active</span>
                  </label>

                  <button className="secondary-button danger-button" type="button" onClick={() => removeArrayItem("machineModules", module.id, "module")}>
                    <Trash2 size={18} />
                    Delete
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="form-card full-span">
          <MaterialHeader
            title="Nozzles"
            description="Control which nozzle options are active and how they affect machine rate and market estimate."
            onAdd={addNozzle}
          />

          <div className="material-settings-list">
            {settings.nozzles.map((nozzle) => (
              <div className="material-settings-row" key={nozzle.id}>
                <div className="form-grid material-settings-grid">
                  <Field label="Nozzle Label" type="text" value={nozzle.label} onChange={(value) => updateArrayItem("nozzles", nozzle.id, "label", value)} />
                  <Field label="Diameter" value={nozzle.diameter} onChange={(value) => updateArrayItem("nozzles", nozzle.id, "diameter", value)} />
                  <Field label="Rate Add ($/hr)" value={nozzle.machineRateAdd} onChange={(value) => updateArrayItem("nozzles", nozzle.id, "machineRateAdd", value)} />
                  <Field label="Market Multiplier" value={nozzle.marketMultiplier} onChange={(value) => updateArrayItem("nozzles", nozzle.id, "marketMultiplier", value)} />

                  <label className="field checkbox-field material-active-field">
                    <input type="checkbox" checked={Boolean(nozzle.active)} onChange={(event) => updateArrayItem("nozzles", nozzle.id, "active", event.target.checked)} />
                    <span>Active</span>
                  </label>

                  <button className="secondary-button danger-button" type="button" onClick={() => removeArrayItem("nozzles", nozzle.id, "nozzle")}>
                    <Trash2 size={18} />
                    Delete
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="form-card full-span">
          <MaterialHeader
            title="CAD Charge Tiers"
            description="These appear in the calculator as selectable CAD estimate levels."
            onAdd={addCadPreset}
          />

          <div className="material-settings-list">
            {settings.cadPresets.map((preset) => (
              <div className="material-settings-row" key={preset.id}>
                <div className="form-grid material-settings-grid">
                  <Field label="Tier Name" type="text" value={preset.label} onChange={(value) => updateArrayItem("cadPresets", preset.id, "label", value)} />
                  <Field label="Amount" value={preset.amount} onChange={(value) => updateArrayItem("cadPresets", preset.id, "amount", value)} />

                  <label className="field checkbox-field material-active-field">
                    <input type="checkbox" checked={Boolean(preset.active)} onChange={(event) => updateArrayItem("cadPresets", preset.id, "active", event.target.checked)} />
                    <span>Active</span>
                  </label>

                  <button className="secondary-button danger-button" type="button" onClick={() => removeArrayItem("cadPresets", preset.id, "CAD tier")}>
                    <Trash2 size={18} />
                    Delete
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="form-card full-span">
          <MaterialHeader
            title="3D Print Materials"
            description="Cost per gram and standard/specialty grouping."
            onAdd={addPrintMaterial}
          />

          <div className="material-settings-list">
            {settings.printMaterials.map((material) => (
              <div className="material-settings-row" key={material.id}>
                <div className="form-grid material-settings-grid">
                  <Field label="Material Name" type="text" value={material.label} onChange={(value) => updateArrayItem("printMaterials", material.id, "label", value)} />
                  <Field label="Cost Per Gram" value={material.costPerGram} onChange={(value) => updateArrayItem("printMaterials", material.id, "costPerGram", value)} />

                  <label className="field">
                    <span>Material Group</span>
                    <select value={material.group} onChange={(event) => updateArrayItem("printMaterials", material.id, "group", event.target.value)}>
                      <option value="standard">Standard</option>
                      <option value="specialty">Specialty</option>
                    </select>
                  </label>

                  <label className="field checkbox-field material-active-field">
                    <input type="checkbox" checked={Boolean(material.active)} onChange={(event) => updateArrayItem("printMaterials", material.id, "active", event.target.checked)} />
                    <span>Active</span>
                  </label>

                  <button className="secondary-button danger-button" type="button" onClick={() => removeArrayItem("printMaterials", material.id, "print material")}>
                    <Trash2 size={18} />
                    Delete
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="form-card full-span">
          <MaterialHeader
            title="Laser Engraving Materials"
            description="Add metals like titanium/stainless steel, customer-provided items, wood, acrylic, patches, and custom blanks."
            onAdd={() => addSheetMaterial("engravingMaterials")}
          />

          <div className="material-settings-list">
            {settings.engravingMaterials.map((material) => (
              <div className="material-settings-row" key={material.id}>
                <div className="form-grid material-settings-grid">
                  <Field label="Material Name" type="text" value={material.label} onChange={(value) => updateArrayItem("engravingMaterials", material.id, "label", value)} />
                  <Field label="Pack Cost" value={material.packCost} onChange={(value) => updateArrayItem("engravingMaterials", material.id, "packCost", value)} />
                  <Field label="Pack Count" value={material.packCount} step="1" onChange={(value) => updateArrayItem("engravingMaterials", material.id, "packCount", value)} />
                  <Field label="Colors / Finish" type="text" value={material.colors} onChange={(value) => updateArrayItem("engravingMaterials", material.id, "colors", value)} />

                  <label className="field">
                    <span>Material Type</span>
                    <select value={material.materialType || "custom"} onChange={(event) => updateArrayItem("engravingMaterials", material.id, "materialType", event.target.value)}>
                      <option value="customer-provided">Customer Provided</option>
                      <option value="metal">Metal</option>
                      <option value="wood">Wood</option>
                      <option value="acrylic">Acrylic</option>
                      <option value="leather">Leather / Leatherette</option>
                      <option value="paper">Paper / Cardstock</option>
                      <option value="custom">Custom</option>
                    </select>
                  </label>

                  <label className="field checkbox-field material-active-field">
                    <input type="checkbox" checked={Boolean(material.active)} onChange={(event) => updateArrayItem("engravingMaterials", material.id, "active", event.target.checked)} />
                    <span>Active</span>
                  </label>

                  <button className="secondary-button danger-button" type="button" onClick={() => removeArrayItem("engravingMaterials", material.id, "engraving material")}>
                    <Trash2 size={18} />
                    Delete
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="form-card full-span">
          <MaterialHeader
            title="Vinyl / Cutter Materials"
            description="Vinyl sheets, transfer tape, HTV, and specialty cutting materials."
            onAdd={() => addSheetMaterial("vinylMaterials")}
          />

          <div className="material-settings-list">
            {settings.vinylMaterials.map((material) => (
              <div className="material-settings-row" key={material.id}>
                <div className="form-grid material-settings-grid">
                  <Field label="Material Name" type="text" value={material.label} onChange={(value) => updateArrayItem("vinylMaterials", material.id, "label", value)} />
                  <Field label="Pack Cost" value={material.packCost} onChange={(value) => updateArrayItem("vinylMaterials", material.id, "packCost", value)} />
                  <Field label="Pack Count" value={material.packCount} step="1" onChange={(value) => updateArrayItem("vinylMaterials", material.id, "packCount", value)} />
                  <Field label="Colors" type="text" value={material.colors} onChange={(value) => updateArrayItem("vinylMaterials", material.id, "colors", value)} />

                  <label className="field checkbox-field material-active-field">
                    <input type="checkbox" checked={Boolean(material.active)} onChange={(event) => updateArrayItem("vinylMaterials", material.id, "active", event.target.checked)} />
                    <span>Active</span>
                  </label>

                  <button className="secondary-button danger-button" type="button" onClick={() => removeArrayItem("vinylMaterials", material.id, "vinyl material")}>
                    <Trash2 size={18} />
                    Delete
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}