import { useState } from "react";
import { Plus, RotateCcw, Save, Trash2 } from "lucide-react";

const DEFAULT_SETTINGS = {
  businessName: "Overkill Solutions",
  defaultTaxPercent: 7,
  defaultDepositPercent: 40,
  invoiceFooter:
    "Generated by Overkill Solutions Internal Production System",

  machineRates: {
    p1s: 3,
    x1c: 3,
    h2sPrint: 3,
    h2sLaser10w: 4,
    h2sLaser40w: 6,
    h2sCutter: 4,
  },

  cadPresets: {
    simple: 30,
    moderate: 80,
    complex: 150,
  },

  setupFees: {
    basic: 5,
    moderate: 15,
    advanced: 30,
  },

  bufferCurve: {
    under50: 20,
    under100: 15,
    under200: 12,
    under400: 10,
    over400: 8,
  },

  printMaterials: [
    { id: "pla", label: "PLA", costPerGram: 0.03, group: "standard", active: true },
    { id: "petg", label: "PETG", costPerGram: 0.03, group: "standard", active: true },
    { id: "abs", label: "ABS", costPerGram: 0.03, group: "standard", active: true },
    { id: "asa", label: "ASA", costPerGram: 0.05, group: "specialty", active: true },
    { id: "tpu", label: "TPU", costPerGram: 0.05, group: "specialty", active: true },
    { id: "pc", label: "PC", costPerGram: 0.06, group: "specialty", active: true },
    { id: "carbon-fiber", label: "Carbon Fiber", costPerGram: 0.07, group: "specialty", active: true },
  ],

  engravingMaterials: [
    { id: "none", label: "None / Customer Provided", packCost: 0, packCount: 1, colors: "N/A", active: true },
    { id: "aluminum-card", label: "Aluminum Card", packCost: 3.89, packCount: 1, colors: "Black, Silver, Red, Blue, Gold, Rainbow", active: true },
    { id: "stainless-round-tag", label: "Round Stainless Steel Tag", packCost: 6.89, packCount: 5, colors: "Stainless", active: true },
    { id: "basswood-2mm", label: "2mm Basswood Plywood", packCost: 13.89, packCount: 6, colors: "Natural", active: true },
    { id: "basswood-3mm", label: "3mm Basswood Plywood", packCost: 14.89, packCount: 6, colors: "Natural", active: true },
    { id: "bamboo-3mm", label: "3mm Bamboo Board", packCost: 28.89, packCount: 6, colors: "Natural Bamboo", active: true },
    { id: "birch-3mm", label: "3mm Birch Plywood", packCost: 31.89, packCount: 6, colors: "Natural Birch", active: true },
    { id: "sapele-3mm", label: "3mm Sapele Plywood", packCost: 33.89, packCount: 6, colors: "Sapele", active: true },
    { id: "black-walnut-3mm", label: "3mm Black Walnut Plywood", packCost: 30.89, packCount: 6, colors: "Black Walnut", active: true },
    { id: "cork-2mm", label: "2mm Cork Sheet", packCost: 8.89, packCount: 4, colors: "Natural Cork", active: true },
    { id: "acrylic-opaque-glossy", label: "3mm Opaque Glossy Acrylic", packCost: 17.89, packCount: 3, colors: "Black, Red, Orange, Yellow, Green", active: true },
    { id: "pu-leatherette", label: "Pebbled PU Leatherette Fabric", packCost: 14.89, packCount: 5, colors: "Black, White, Brown, Gray", active: true },
    { id: "pu-iron-on-patch", label: "Rectangular PU Iron-on Patch", packCost: 12.89, packCount: 10, colors: "Black", active: true },
    { id: "cardstock-250g", label: "250g Cardstock", packCost: 6.89, packCount: 25, colors: "Black", active: true },
    { id: "kraft-paper-a4", label: "A4 200g Kraft Paper", packCost: 4.89, packCount: 25, colors: "Kraft Brown", active: true },
    { id: "greeting-card", label: "Pearlescent White Greeting Card Set", packCost: 5.89, packCount: 2, colors: "Pearlescent White", active: true },
  ],

  vinylMaterials: [
    { id: "none", label: "None / Customer Provided", packCost: 0, packCount: 1, colors: "N/A", active: true },
    { id: "matte-removable-vinyl", label: "Matte Removable Vinyl", packCost: 9.89, packCount: 10, colors: "Black, Red, Orange, Yellow, Green, Blue, Silver, White", active: true },
    { id: "carbon-fiber-removable-vinyl", label: "Carbon Fiber Textured Removable Vinyl", packCost: 9.89, packCount: 10, colors: "Black Carbon Fiber", active: true },
    { id: "printable-vinyl-paper", label: "White Matte Printable Vinyl Sticker Paper", packCost: 8.89, packCount: 25, colors: "White", active: true },
    { id: "reflective-decal-sheet", label: "Light Gray Reflective Decal Sheet", packCost: 9.89, packCount: 5, colors: "Light Gray Reflective", active: true },
    { id: "transfer-tape", label: "Transfer Tape", packCost: 7.89, packCount: 10, colors: "Clear Grid", active: true },
    { id: "matte-heat-transfer-vinyl", label: "Matte Heat Transfer Vinyl", packCost: 10.89, packCount: 10, colors: "Black, Red, Pink, Orange, Yellow, Cream, Green, Blue, Gray, White", active: true },
    { id: "chrome-heat-transfer-vinyl", label: "Chrome Foil Heat Transfer Vinyl", packCost: 16.89, packCount: 10, colors: "Chrome Silver", active: true },
  ],

  paymentMethods: ["Venmo", "Cash", "Cash App", "PayPal", "Zelle"],
};

function mergeSettings(saved) {
  return {
    ...DEFAULT_SETTINGS,
    ...saved,
    machineRates: { ...DEFAULT_SETTINGS.machineRates, ...(saved?.machineRates || {}) },
    cadPresets: { ...DEFAULT_SETTINGS.cadPresets, ...(saved?.cadPresets || {}) },
    setupFees: { ...DEFAULT_SETTINGS.setupFees, ...(saved?.setupFees || {}) },
    bufferCurve: { ...DEFAULT_SETTINGS.bufferCurve, ...(saved?.bufferCurve || {}) },
    printMaterials: saved?.printMaterials || DEFAULT_SETTINGS.printMaterials,
    engravingMaterials: saved?.engravingMaterials || DEFAULT_SETTINGS.engravingMaterials,
    vinylMaterials: saved?.vinylMaterials || DEFAULT_SETTINGS.vinylMaterials,
  };
}

function getInitialSettings() {
  try {
    const saved = localStorage.getItem("overkill_settings");
    return saved ? mergeSettings(JSON.parse(saved)) : DEFAULT_SETTINGS;
  } catch {
    return DEFAULT_SETTINGS;
  }
}

function makeId(label) {
  return String(label || "new-material")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function Field({ label, value, onChange, type = "number", step = "0.01" }) {
  return (
    <label className="field">
      <span>{label}</span>
      <input
        type={type}
        value={value}
        step={type === "number" ? step : undefined}
        onChange={(event) => onChange(event.target.value)}
      />
    </label>
  );
}

function MaterialHeader({ title, description, onAdd }) {
  return (
    <div className="page-heading-row material-section-heading">
      <div>
        <h3 className="card-title">{title}</h3>
        <p className="muted-text">{description}</p>
      </div>

      <button className="secondary-button" type="button" onClick={onAdd}>
        <Plus size={18} />
        Add
      </button>
    </div>
  );
}

export default function SettingsPage() {
  const [settings, setSettings] = useState(getInitialSettings);
  const [saveMessage, setSaveMessage] = useState("");

  function update(key, value) {
    setSettings((current) => ({
      ...current,
      [key]: value,
    }));
  }

  function updateNested(section, key, value) {
    setSettings((current) => ({
      ...current,
      [section]: {
        ...current[section],
        [key]: value,
      },
    }));
  }

  function updatePaymentMethods(value) {
    const methods = value
      .split("\n")
      .map((item) => item.trim())
      .filter(Boolean);

    update("paymentMethods", methods);
  }

  function updateMaterial(section, materialId, key, value) {
    setSettings((current) => ({
      ...current,
      [section]: current[section].map((material) => {
        if (material.id !== materialId) return material;

        const nextMaterial = {
          ...material,
          [key]: value,
        };

        if (key === "label") {
          nextMaterial.id = makeId(value);
        }

        return nextMaterial;
      }),
    }));
  }

  function addPrintMaterial() {
    const newMaterial = {
      id: `new-print-material-${Date.now()}`,
      label: "New Print Material",
      costPerGram: 0.03,
      group: "standard",
      active: true,
    };

    setSettings((current) => ({
      ...current,
      printMaterials: [...current.printMaterials, newMaterial],
    }));
  }

  function addSheetMaterial(section) {
    const newMaterial = {
      id: `new-sheet-material-${Date.now()}`,
      label: "New Material",
      packCost: 0,
      packCount: 1,
      colors: "Black, White",
      active: true,
    };

    setSettings((current) => ({
      ...current,
      [section]: [...current[section], newMaterial],
    }));
  }

  function removeMaterial(section, materialId) {
    const confirmed = window.confirm("Delete this material from settings?");

    if (!confirmed) return;

    setSettings((current) => ({
      ...current,
      [section]: current[section].filter((material) => material.id !== materialId),
    }));
  }

  function saveSettings() {
    localStorage.setItem("overkill_settings", JSON.stringify(settings));
    setSaveMessage("Settings saved locally.");
  }

  function resetSettings() {
    const confirmed = window.confirm(
      "Reset settings back to Overkill defaults? This will also reset material lists."
    );

    if (!confirmed) return;

    setSettings(DEFAULT_SETTINGS);
    localStorage.setItem("overkill_settings", JSON.stringify(DEFAULT_SETTINGS));
    setSaveMessage("Settings reset to defaults.");
  }

  return (
    <section className="page-panel">
      <div className="page-heading-row">
        <div>
          <h2 className="section-title brand-font">Settings</h2>
          <p className="muted-text">
            Persistent app defaults for rates, materials, deposits, taxes, setup fees, buffer curve, and payment methods.
          </p>

          {saveMessage && <p className="helper-note">{saveMessage}</p>}
        </div>

        <div className="settings-action-row">
          <button className="secondary-button" onClick={resetSettings}>
            <RotateCcw size={18} />
            Reset
          </button>

          <button className="primary-button settings-save-button" onClick={saveSettings}>
            <Save size={18} />
            Save Settings
          </button>
        </div>
      </div>

      <div className="settings-grid">
        <div className="form-card">
          <h3 className="card-title">Business Defaults</h3>

          <div className="form-grid">
            <Field
              label="Business Name"
              type="text"
              value={settings.businessName}
              onChange={(value) => update("businessName", value)}
            />

            <Field
              label="Default Tax %"
              value={settings.defaultTaxPercent}
              onChange={(value) => update("defaultTaxPercent", value)}
            />

            <Field
              label="Default Deposit %"
              value={settings.defaultDepositPercent}
              onChange={(value) => update("defaultDepositPercent", value)}
            />
          </div>

          <label className="field single-row-gap">
            <span>Invoice / PDF Footer Text</span>
            <textarea
              value={settings.invoiceFooter}
              onChange={(event) => update("invoiceFooter", event.target.value)}
            />
          </label>
        </div>

        <div className="form-card">
          <h3 className="card-title">Machine Rates</h3>

          <div className="form-grid">
            <Field label="P1S Print Rate ($/hr)" value={settings.machineRates.p1s} onChange={(value) => updateNested("machineRates", "p1s", value)} />
            <Field label="X1C Print Rate ($/hr)" value={settings.machineRates.x1c} onChange={(value) => updateNested("machineRates", "x1c", value)} />
            <Field label="H2S Print Rate ($/hr)" value={settings.machineRates.h2sPrint} onChange={(value) => updateNested("machineRates", "h2sPrint", value)} />
            <Field label="H2S 10W Laser Rate ($/hr)" value={settings.machineRates.h2sLaser10w} onChange={(value) => updateNested("machineRates", "h2sLaser10w", value)} />
            <Field label="H2S 40W Laser Rate ($/hr)" value={settings.machineRates.h2sLaser40w} onChange={(value) => updateNested("machineRates", "h2sLaser40w", value)} />
            <Field label="H2S Cutter Rate ($/hr)" value={settings.machineRates.h2sCutter} onChange={(value) => updateNested("machineRates", "h2sCutter", value)} />
          </div>
        </div>

        <div className="form-card">
          <h3 className="card-title">CAD Presets</h3>

          <div className="form-grid">
            <Field label="Simple CAD" value={settings.cadPresets.simple} onChange={(value) => updateNested("cadPresets", "simple", value)} />
            <Field label="Moderate CAD" value={settings.cadPresets.moderate} onChange={(value) => updateNested("cadPresets", "moderate", value)} />
            <Field label="Complex CAD" value={settings.cadPresets.complex} onChange={(value) => updateNested("cadPresets", "complex", value)} />
          </div>
        </div>

        <div className="form-card">
          <h3 className="card-title">Setup Fees</h3>

          <div className="form-grid">
            <Field label="Basic Setup" value={settings.setupFees.basic} onChange={(value) => updateNested("setupFees", "basic", value)} />
            <Field label="Moderate Setup" value={settings.setupFees.moderate} onChange={(value) => updateNested("setupFees", "moderate", value)} />
            <Field label="Advanced Setup" value={settings.setupFees.advanced} onChange={(value) => updateNested("setupFees", "advanced", value)} />
          </div>
        </div>

        <div className="form-card">
          <h3 className="card-title">Buffer Curve</h3>

          <div className="form-grid">
            <Field label="$0–50 Buffer %" value={settings.bufferCurve.under50} onChange={(value) => updateNested("bufferCurve", "under50", value)} />
            <Field label="$50–100 Buffer %" value={settings.bufferCurve.under100} onChange={(value) => updateNested("bufferCurve", "under100", value)} />
            <Field label="$100–200 Buffer %" value={settings.bufferCurve.under200} onChange={(value) => updateNested("bufferCurve", "under200", value)} />
            <Field label="$200–400 Buffer %" value={settings.bufferCurve.under400} onChange={(value) => updateNested("bufferCurve", "under400", value)} />
            <Field label="$400+ Buffer %" value={settings.bufferCurve.over400} onChange={(value) => updateNested("bufferCurve", "over400", value)} />
          </div>
        </div>

        <div className="form-card">
          <h3 className="card-title">Payment Methods</h3>

          <label className="field">
            <span>One payment method per line</span>
            <textarea
              value={settings.paymentMethods.join("\n")}
              onChange={(event) => updatePaymentMethods(event.target.value)}
            />
          </label>
        </div>

        <div className="form-card full-span">
          <MaterialHeader
            title="3D Print Materials"
            description="Cost per gram and standard/specialty grouping. Next step will wire these into the calculator."
            onAdd={addPrintMaterial}
          />

          <div className="material-settings-list">
            {settings.printMaterials.map((material) => (
              <div className="material-settings-row" key={material.id}>
                <div className="form-grid material-settings-grid">
                  <Field
                    label="Material Name"
                    type="text"
                    value={material.label}
                    onChange={(value) => updateMaterial("printMaterials", material.id, "label", value)}
                  />

                  <Field
                    label="Cost Per Gram"
                    value={material.costPerGram}
                    onChange={(value) => updateMaterial("printMaterials", material.id, "costPerGram", value)}
                  />

                  <label className="field">
                    <span>Material Group</span>
                    <select
                      value={material.group}
                      onChange={(event) => updateMaterial("printMaterials", material.id, "group", event.target.value)}
                    >
                      <option value="standard">Standard</option>
                      <option value="specialty">Specialty</option>
                    </select>
                  </label>

                  <label className="field checkbox-field material-active-field">
                    <input
                      type="checkbox"
                      checked={Boolean(material.active)}
                      onChange={(event) => updateMaterial("printMaterials", material.id, "active", event.target.checked)}
                    />
                    <span>Active</span>
                  </label>

                  <button
                    className="secondary-button danger-button"
                    type="button"
                    onClick={() => removeMaterial("printMaterials", material.id)}
                  >
                    <Trash2 size={18} />
                    Delete
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="form-card full-span">
          <MaterialHeader
            title="Laser Engraving Materials"
            description="Pack cost, pack count, and colors for material cost estimation."
            onAdd={() => addSheetMaterial("engravingMaterials")}
          />

          <div className="material-settings-list">
            {settings.engravingMaterials.map((material) => (
              <div className="material-settings-row" key={material.id}>
                <div className="form-grid material-settings-grid">
                  <Field
                    label="Material Name"
                    type="text"
                    value={material.label}
                    onChange={(value) => updateMaterial("engravingMaterials", material.id, "label", value)}
                  />

                  <Field
                    label="Pack Cost"
                    value={material.packCost}
                    onChange={(value) => updateMaterial("engravingMaterials", material.id, "packCost", value)}
                  />

                  <Field
                    label="Pack Count"
                    value={material.packCount}
                    step="1"
                    onChange={(value) => updateMaterial("engravingMaterials", material.id, "packCount", value)}
                  />

                  <Field
                    label="Colors"
                    type="text"
                    value={material.colors}
                    onChange={(value) => updateMaterial("engravingMaterials", material.id, "colors", value)}
                  />

                  <label className="field checkbox-field material-active-field">
                    <input
                      type="checkbox"
                      checked={Boolean(material.active)}
                      onChange={(event) => updateMaterial("engravingMaterials", material.id, "active", event.target.checked)}
                    />
                    <span>Active</span>
                  </label>

                  <button
                    className="secondary-button danger-button"
                    type="button"
                    onClick={() => removeMaterial("engravingMaterials", material.id)}
                  >
                    <Trash2 size={18} />
                    Delete
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="form-card full-span">
          <MaterialHeader
            title="Vinyl / Cutter Materials"
            description="Vinyl sheets, transfer tape, HTV, and specialty cutting materials."
            onAdd={() => addSheetMaterial("vinylMaterials")}
          />

          <div className="material-settings-list">
            {settings.vinylMaterials.map((material) => (
              <div className="material-settings-row" key={material.id}>
                <div className="form-grid material-settings-grid">
                  <Field
                    label="Material Name"
                    type="text"
                    value={material.label}
                    onChange={(value) => updateMaterial("vinylMaterials", material.id, "label", value)}
                  />

                  <Field
                    label="Pack Cost"
                    value={material.packCost}
                    onChange={(value) => updateMaterial("vinylMaterials", material.id, "packCost", value)}
                  />

                  <Field
                    label="Pack Count"
                    value={material.packCount}
                    step="1"
                    onChange={(value) => updateMaterial("vinylMaterials", material.id, "packCount", value)}
                  />

                  <Field
                    label="Colors"
                    type="text"
                    value={material.colors}
                    onChange={(value) => updateMaterial("vinylMaterials", material.id, "colors", value)}
                  />

                  <label className="field checkbox-field material-active-field">
                    <input
                      type="checkbox"
                      checked={Boolean(material.active)}
                      onChange={(event) => updateMaterial("vinylMaterials", material.id, "active", event.target.checked)}
                    />
                    <span>Active</span>
                  </label>

                  <button
                    className="secondary-button danger-button"
                    type="button"
                    onClick={() => removeMaterial("vinylMaterials", material.id)}
                  >
                    <Trash2 size={18} />
                    Delete
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}