import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import overkillLogo from "../assets/logos/overkill_main.png";
import overkillMark from "../assets/logos/overkill_mark.png";

const RED = [214, 40, 40];
const DARK = [18, 18, 18];
const GRAY = [105, 105, 105];
const LIGHT = [235, 235, 235];
const SOFT_RED = [252, 235, 235];

const PAGE = {
  left: 14,
  right: 196,
  bottom: 272,
};

const START_MARKER = "OVERKILL_DATA_START";
const END_MARKER = "OVERKILL_DATA_END";

function money(value) {
  return Number(value || 0).toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
  });
}

function num(value) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : 0;
}

function safeFileName(value) {
  return String(value || "document")
    .replace(/[^a-z0-9-_ ]/gi, "")
    .replace(/\s+/g, "-")
    .toLowerCase();
}

function encodeBase64Unicode(value) {
  const json = JSON.stringify(value);
  const bytes = new TextEncoder().encode(json);

  let binary = "";
  const chunkSize = 0x8000;

  for (let index = 0; index < bytes.length; index += chunkSize) {
    const chunk = bytes.subarray(index, index + chunkSize);
    binary += String.fromCharCode(...chunk);
  }

  return btoa(binary);
}

function addEmbeddedData(doc, payload) {
  const encoded = encodeBase64Unicode(payload);
  const fullText = `${START_MARKER}${encoded}${END_MARKER}`;
  const chunks = fullText.match(/.{1,90}/g) || [];
  const originalPage = doc.internal.getCurrentPageInfo().pageNumber;

  doc.addPage();
  doc.setFont("helvetica", "normal");
  doc.setFontSize(1);
  doc.setTextColor(255, 255, 255);

  let y = 4;

  chunks.forEach((chunk) => {
    if (y > 285) {
      doc.addPage();
      doc.setFont("helvetica", "normal");
      doc.setFontSize(1);
      doc.setTextColor(255, 255, 255);
      y = 4;
    }

    doc.text(chunk, 2, y);
    y += 2;
  });

  doc.setPage(originalPage);
}

function buildAspectList(jobAspects = {}) {
  const labels = [];

  if (jobAspects.cad) labels.push("CAD Modeling");
  if (jobAspects.printing) labels.push("3D Printing");
  if (jobAspects.engraving) labels.push("Laser Engraving");
  if (jobAspects.vinyl) labels.push("Vinyl Cutting");
  if (jobAspects.custom) labels.push("Custom Fabrication");

  return labels.length ? labels.join(", ") : "Custom Work";
}

function getInvoiceNumber(job) {
  if (job.invoiceNumber) return job.invoiceNumber;
  if (job.recordNumber) return `INV-${job.recordNumber}`;
  if (job.jobNumber) return job.jobNumber.replace("J-", "INV-");
  return "INV-DRAFT";
}

function getRevisionRows(record) {
  const rows = [];
  const revisionNumber = Number(record.revisionNumber || 0);

  if (revisionNumber > 0) {
    rows.push(["Revision", `Revision ${revisionNumber}`]);
  } else if (record.sourceQuoteNumber) {
    rows.push(["Revision", "Copied Quote"]);
  }

  if (record.sourceQuoteNumber) {
    const label = revisionNumber > 0 ? "Revised From" : "Copied From";
    rows.push([label, record.sourceQuoteNumber]);
  }

  if (record.originalRecordNumber && record.originalRecordNumber !== record.recordNumber) {
    rows.push(["Original Record", `Q-${record.originalRecordNumber}`]);
  }

  if (record.sourceRecordNumber && record.sourceRecordNumber !== record.recordNumber) {
    rows.push(["Source Record", `Q-${record.sourceRecordNumber}`]);
  }

  return rows;
}

function getRevisionSummary(record) {
  const revisionNumber = Number(record.revisionNumber || 0);

  if (revisionNumber > 0 && record.sourceQuoteNumber) {
    return `Revision ${revisionNumber} based on ${record.sourceQuoteNumber}.`;
  }

  if (revisionNumber > 0) return `Revision ${revisionNumber}.`;
  if (record.sourceQuoteNumber) return `Copied from ${record.sourceQuoteNumber}.`;

  return "";
}

function addFooter(doc) {
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.setDrawColor(...LIGHT);
  doc.line(PAGE.left, pageHeight - 18, PAGE.right, pageHeight - 18);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text("Overkill Solutions", PAGE.left, pageHeight - 11);

  doc.text(
    "Generated by Overkill Solutions Internal Production System",
    PAGE.right,
    pageHeight - 11,
    { align: "right" }
  );
}

function addHeader(doc, title, numberText, copyLabel = "CUSTOMER COPY") {
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(...DARK);
  doc.rect(0, 0, pageWidth, 44, "F");

  doc.setFillColor(...RED);
  doc.rect(0, 42, pageWidth, 3, "F");

  try {
    doc.addImage(overkillLogo, "PNG", PAGE.left, 8, 62, 20);
  } catch {
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text("OVERKILL SOLUTIONS", PAGE.left, 20);
  }

  try {
    doc.addImage(overkillMark, "PNG", 180, 8, 16, 16);
  } catch {
    // optional logo fallback
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text(copyLabel, PAGE.right, 34, { align: "right" });

  doc.setTextColor(...DARK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text(title, PAGE.left, 59);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...GRAY);
  doc.text(numberText, PAGE.left, 66);

  addFooter(doc);

  return 76;
}

function addContinuationHeader(doc, title, numberText) {
  doc.addPage();

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...RED);
  doc.text(`OVERKILL SOLUTIONS — ${title}`, PAGE.left, 14);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.text(numberText, PAGE.right, 14, { align: "right" });

  doc.setDrawColor(...LIGHT);
  doc.line(PAGE.left, 18, PAGE.right, 18);

  addFooter(doc);

  return 28;
}

function ensureSpace(doc, y, neededHeight, title, numberText) {
  if (y + neededHeight <= PAGE.bottom) return y;
  return addContinuationHeader(doc, title, numberText);
}

function addSectionTitle(doc, titleText, y, documentTitle, numberText) {
  y = ensureSpace(doc, y, 18, documentTitle, numberText);

  doc.setFont("helvetica", "bold");
  doc.setTextColor(...RED);
  doc.setFontSize(13);
  doc.text(titleText, PAGE.left, y);

  doc.setDrawColor(...LIGHT);
  doc.line(PAGE.left, y + 3, PAGE.right, y + 3);

  return y + 10;
}

function addWrappedText(doc, text, y, documentTitle, numberText) {
  doc.setFont("helvetica", "normal");
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(9);

  const lines = doc.splitTextToSize(text || "None provided.", 182);
  const lineHeight = 5;

  y = ensureSpace(doc, y, lines.length * lineHeight + 8, documentTitle, numberText);

  let currentY = y;

  lines.forEach((line) => {
    if (currentY + lineHeight > PAGE.bottom) {
      currentY = addContinuationHeader(doc, documentTitle, numberText);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(40, 40, 40);
      doc.setFontSize(9);
    }

    doc.text(line, PAGE.left, currentY);
    currentY += lineHeight;
  });

  return currentY + 8;
}

function buildContactRows(record) {
  const rows = [["Customer", record.customerName || "Unnamed Customer"]];

  if (record.customerPhone || record.formData?.customerPhone) {
    rows.push(["Phone", record.customerPhone || record.formData?.customerPhone || ""]);
  }

  if (record.customerEmail || record.formData?.customerEmail) {
    rows.push(["Email", record.customerEmail || record.formData?.customerEmail || ""]);
  }

  if (record.customerAddress || record.formData?.customerAddress) {
    rows.push(["Address", record.customerAddress || record.formData?.customerAddress || ""]);
  }

  const preferredContact =
    record.preferredContactMethod || record.formData?.preferredContactMethod;

  if (preferredContact && preferredContact !== "Not Set") {
    rows.push(["Preferred Contact", preferredContact]);
  }

  const preferredPayment =
    record.preferredPaymentMethod || record.formData?.preferredPaymentMethod;

  if (preferredPayment && preferredPayment !== "Not Set") {
    rows.push(["Preferred Payment", preferredPayment]);
  }

  return rows;
}

function buildQueueRows(record) {
  const rows = [];

  if (record.priority) rows.push(["Priority", record.priority]);
  if (record.dueDate) rows.push(["Due Date", record.dueDate]);
  if (record.queueNotes) rows.push(["Queue Notes", record.queueNotes]);

  return rows;
}

function addInfoBlock(doc, record, startY, title, numberText, extraRows = []) {
  const date = new Date(
    record.createdAt || record.approvedAt || Date.now()
  ).toLocaleDateString();

  const rows = [
    ...buildContactRows(record),
    ["Project", record.jobName || "Untitled Project"],
    ["Date", date],
    ["Services", buildAspectList(record.jobAspects)],
    ...getRevisionRows(record),
    ...buildQueueRows(record),
    ...extraRows,
  ];

  startY = ensureSpace(doc, startY, rows.length * 8 + 12, title, numberText);

  autoTable(doc, {
    startY,
    body: rows,
    theme: "plain",
    styles: {
      fontSize: 10,
      cellPadding: 2.2,
      overflow: "linebreak",
    },
    columnStyles: {
      0: {
        fontStyle: "bold",
        textColor: RED,
        cellWidth: 40,
      },
      1: {
        textColor: [30, 30, 30],
        cellWidth: 142,
      },
    },
    margin: {
      left: PAGE.left,
      right: PAGE.left,
    },
  });

  return doc.lastAutoTable.finalY + 9;
}

function addTotalsBox(doc, rows, startY, documentTitle, numberText) {
  if (!rows.length) return startY;

  startY = ensureSpace(doc, startY, rows.length * 11 + 18, documentTitle, numberText);

  autoTable(doc, {
    startY,
    body: rows,
    theme: "grid",
    margin: {
      left: PAGE.left,
      right: PAGE.left,
    },
    pageBreak: "auto",
    rowPageBreak: "avoid",
    styles: {
      fontSize: 10,
      cellPadding: 4.5,
      lineColor: [220, 220, 220],
      lineWidth: 0.2,
      overflow: "linebreak",
    },
    alternateRowStyles: {
      fillColor: [250, 250, 250],
    },
    columnStyles: {
      0: {
        fontStyle: "bold",
        textColor: [55, 55, 55],
        cellWidth: 120,
      },
      1: {
        halign: "right",
        fontStyle: "bold",
      },
    },
    didParseCell(data) {
      if (data.row.index === rows.length - 1) {
        data.cell.styles.fillColor = RED;
        data.cell.styles.textColor = [255, 255, 255];
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.fontSize = 11;
      }
    },
    didDrawPage() {
      addFooter(doc);
    },
  });

  return doc.lastAutoTable.finalY + 11;
}

function addTable(doc, options, documentTitle, numberText) {
  const startY = ensureSpace(doc, options.startY, 40, documentTitle, numberText);

  autoTable(doc, {
    ...options,
    startY,
    margin: {
      left: PAGE.left,
      right: PAGE.left,
    },
    pageBreak: "auto",
    rowPageBreak: "avoid",
    didDrawPage() {
      addFooter(doc);
    },
  });

  return doc.lastAutoTable.finalY + 10;
}

function addAmountDueBox(doc, { label, amount, subLabel, paid, total }, y, documentTitle, numberText) {
  y = ensureSpace(doc, y, 42, documentTitle, numberText);

  doc.setFillColor(...SOFT_RED);
  doc.setDrawColor(...RED);
  doc.roundedRect(PAGE.left, y, PAGE.right - PAGE.left, 34, 3, 3, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...RED);
  doc.text(label, PAGE.left + 7, y + 10);

  doc.setFontSize(22);
  doc.setTextColor(...DARK);
  doc.text(money(amount), PAGE.right - 7, y + 14, { align: "right" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(70, 70, 70);

  if (subLabel) {
    doc.text(subLabel, PAGE.left + 7, y + 23);
  }

  if (paid !== undefined || total !== undefined) {
    const paidText = `Paid: ${money(paid || 0)}    Total: ${money(total || 0)}`;
    doc.text(paidText, PAGE.right - 7, y + 24, { align: "right" });
  }

  return y + 44;
}

function addSignatureSection(doc, y, documentTitle, numberText) {
  y = addSectionTitle(doc, "Approval / Signature", y, documentTitle, numberText);
  y = ensureSpace(doc, y, 45, documentTitle, numberText);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(40, 40, 40);

  const approvalText =
    "By signing below, the customer acknowledges the document details, project scope, payment status, and any remaining balance shown on this document.";

  const lines = doc.splitTextToSize(approvalText, 182);
  doc.text(lines, PAGE.left, y);

  y += lines.length * 5 + 14;

  doc.setDrawColor(80, 80, 80);
  doc.line(PAGE.left, y, 105, y);
  doc.line(125, y, PAGE.right, y);

  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.text("Customer Signature", PAGE.left, y + 6);
  doc.text("Date", 125, y + 6);

  return y + 16;
}

function addInternalSignoffSection(doc, y, documentTitle, numberText) {
  y = addSectionTitle(doc, "Internal Production Sign-Off", y, documentTitle, numberText);
  y = ensureSpace(doc, y, 55, documentTitle, numberText);

  const rows = [
    ["Production Started By", ""],
    ["Production Completed By", ""],
    ["Quality Checked By", ""],
    ["Packed / Delivered By", ""],
  ];

  autoTable(doc, {
    startY: y,
    body: rows,
    theme: "grid",
    margin: { left: PAGE.left, right: PAGE.left },
    styles: {
      fontSize: 9,
      cellPadding: 5,
      lineColor: [210, 210, 210],
      lineWidth: 0.2,
    },
    columnStyles: {
      0: {
        fontStyle: "bold",
        textColor: RED,
        cellWidth: 62,
      },
      1: {
        cellWidth: 120,
      },
    },
    didDrawPage() {
      addFooter(doc);
    },
  });

  return doc.lastAutoTable.finalY + 10;
}

function getShippingEstimate(record) {
  return record.shippingEstimate || record.formData?.shippingEstimate || null;
}

function buildShippingRows(record) {
  const shipping = getShippingEstimate(record);

  if (!shipping) return [];

  const rows = [
    ["Shipping Carrier", `${shipping.carrier || "N/A"} — ${shipping.service || "N/A"}`],
    ["Shipment Status", shipping.shipmentStatus || shipping.status || "Estimate"],
    [
      "Package",
      `${shipping.packagePreset || "Custom"} / ${shipping.length || 0} x ${
        shipping.width || 0
      } x ${shipping.height || 0} in / ${shipping.billableWeight || 0} lb billable`,
    ],
    ["Carrier Quote", money(shipping.quotedShipping || 0)],
    [
      "Packaging / Handling",
      money(
        num(shipping.packageCost) +
          num(shipping.packingMaterialCost) +
          num(shipping.handlingFee)
      ),
    ],
    [
      "Insurance / Signature",
      money(num(shipping.insurance) + num(shipping.signatureConfirmation)),
    ],
    ["Shipping Add-On", money(shipping.total || 0)],
  ];

  if (shipping.trackingNumber) rows.push(["Tracking Number", shipping.trackingNumber]);
  if (shipping.trackingUrl) rows.push(["Tracking Link", shipping.trackingUrl]);
  if (shipping.shippedDate) rows.push(["Shipped Date", shipping.shippedDate]);
  if (shipping.deliveredDate) rows.push(["Delivered Date", shipping.deliveredDate]);
  if (shipping.notes) rows.push(["Shipping Notes", shipping.notes]);

  return rows;
}

function getJobAttachments(record) {
  return Array.isArray(record.attachments) ? record.attachments : [];
}

function buildAttachmentRows(record) {
  const attachments = getJobAttachments(record);

  return attachments.map((attachment, index) => [
    `${index + 1}`,
    attachment.type || "Other",
    attachment.name || "Unnamed attachment",
    attachment.url || "No path / URL saved",
    attachment.notes || "",
  ]);
}

function addAttachmentsSectionIfNeeded(doc, job, y, documentTitle, numberText) {
  const rows = buildAttachmentRows(job);

  if (rows.length === 0) return y;

  y = addSectionTitle(doc, "Job Attachments / File Links", y, documentTitle, numberText);

  y = addTable(
    doc,
    {
      startY: y,
      head: [["#", "Type", "Name", "Path / URL / Location", "Notes"]],
      body: rows,
      theme: "grid",
      headStyles: {
        fillColor: RED,
        textColor: [255, 255, 255],
      },
      alternateRowStyles: {
        fillColor: [250, 250, 250],
      },
      styles: {
        fontSize: 7.5,
        cellPadding: 2.4,
        overflow: "linebreak",
      },
      columnStyles: {
        0: { cellWidth: 9, halign: "center" },
        1: { cellWidth: 34, fontStyle: "bold" },
        2: { cellWidth: 40 },
        3: { cellWidth: 62 },
        4: { cellWidth: 37 },
      },
    },
    documentTitle,
    numberText
  );

  return addWrappedText(
    doc,
    "Attachment records are file names, links, or storage locations only. The files themselves are not embedded in this production sheet.",
    y,
    documentTitle,
    numberText
  );
}

function buildFallbackCustomerLines(record) {
  const totals = record.totals || record.quoteSnapshot?.totals || {};
  const form = record.formData || record.quoteSnapshot?.formData || {};
  const rows = [];

  const printTotal =
    num(totals.customerPrintingCost) ||
    num(totals.printMaterialCost) +
      num(totals.machineCost) +
      num(totals.setupFee);

  const cadTotal = num(totals.customerCadCost) || num(totals.cadCost);
  const engravingTotal =
    num(totals.customerEngravingCost) ||
    num(totals.engravingMaterialCost) +
      num(totals.engravingCost);
  const vinylTotal =
    num(totals.customerVinylCost) ||
    num(totals.vinylMaterialCost) +
      num(totals.vinylCost);
  const integrationTotal =
    num(totals.customerIntegrationCost) || num(totals.integrationCost);
  const customTotal = num(totals.customerCustomCost) || num(totals.customCost);
  const finishingTotal =
    num(totals.customerFinishingCost) ||
    num(totals.extraLaborCost) +
      num(form.complexityFee) +
      num(form.finishingFee);
  const shippingTotal =
    num(totals.customerShippingCost) ||
    num(record.shippingEstimate?.total) ||
    num(form.shippingFee);

  if (form.jobAspects?.cad || cadTotal > 0) rows.push(["Design / CAD Work", money(cadTotal)]);
  if (form.jobAspects?.printing || printTotal > 0) rows.push(["3D Printing", money(printTotal)]);
  if (form.jobAspects?.engraving || engravingTotal > 0) rows.push(["Laser Engraving", money(engravingTotal)]);
  if (form.jobAspects?.vinyl || vinylTotal > 0) rows.push(["Vinyl / Cutting Work", money(vinylTotal)]);
  if (integrationTotal > 0) rows.push(["Project Setup / Integration", money(integrationTotal)]);
  if (customTotal > 0) rows.push(["Custom Work", money(customTotal)]);
  if (finishingTotal > 0) rows.push(["Finishing / Cleanup", money(finishingTotal)]);
  if (shippingTotal > 0) rows.push(["Shipping / Delivery", money(shippingTotal)]);

  return rows;
}

function buildCustomerFacingRows(record) {
  const totals = record.totals || record.quoteSnapshot?.totals || {};
  const form = record.formData || record.quoteSnapshot?.formData || {};
  const savedLines = totals.customerFacingLines || [];
  const rows =
    savedLines.length > 0
      ? savedLines.map(([label, value]) => [label, money(value)])
      : buildFallbackCustomerLines(record);

  if (num(form.discount) > 0) {
    rows.push(["Discount", `-${money(form.discount)}`]);
  }

  if (num(totals.tax) > 0) {
    rows.push(["Tax", money(totals.tax)]);
  }

  rows.push(["Final Total", money(record.finalTotal)]);

  return rows.filter((row) => row[1] !== "$0.00" && row[1] !== "-$0.00");
}

function buildInternalRows(record) {
  const totals = record.totals || record.quoteSnapshot?.totals || {};
  const form = record.formData || record.quoteSnapshot?.formData || {};

  return [
    ["CAD Design", money(totals.cadCost)],
    ["3D Print Material", money(totals.printMaterialCost)],
    ["3D Print Machine Time", money(totals.machineCost)],
    ["3D Print Setup", money(totals.setupFee)],
    ["Engraving Material", money(totals.engravingMaterialCost)],
    ["Engraving Service", money(totals.engravingCost)],
    ["Vinyl Material", money(totals.vinylMaterialCost)],
    ["Vinyl Service", money(totals.vinylCost)],
    ["Project Integration", money(totals.integrationCost)],
    ["Custom Fabrication", money(totals.customCost)],
    ["Extra Labor", money(totals.extraLaborCost)],
    ["Internal Buffer", money(totals.quoteBuffer)],
    ["Minimum Adjustment", money(totals.minimumAdjustment)],
    ["Discount", `-${money(form.discount)}`],
    ["Tax", money(totals.tax)],
    ["Final Total", money(record.finalTotal)],
  ].filter((row) => row[1] !== "$0.00" && row[1] !== "-$0.00");
}

function getServiceRows(record, mode = "customer") {
  if (mode === "internal") return buildInternalRows(record);
  return buildCustomerFacingRows(record);
}

function getPaymentTotals(job) {
  const payments = job.paymentEvents || [];

  const totalPaid = payments.reduce((sum, payment) => {
    if (payment.type === "Refund") return sum - num(payment.amount);
    return sum + num(payment.amount);
  }, 0);

  const remaining = Math.max(0, num(job.finalTotal) - totalPaid);

  let status = "Unpaid";
  if (totalPaid > 0 && totalPaid < num(job.finalTotal)) status = "Partially Paid";
  if (totalPaid >= num(job.finalTotal)) {
    status = totalPaid > num(job.finalTotal) ? "Overpaid" : "Paid in Full";
  }

  return { totalPaid, remaining, status };
}

function buildProductionSummary(job) {
  const form = job.formData || job.quoteSnapshot?.formData || {};
  const rows = [];

  const revisionSummary = getRevisionSummary(job);
  if (revisionSummary) rows.push(["Quote Revision", revisionSummary]);

  if (job.priority) rows.push(["Priority", job.priority]);
  if (job.dueDate) rows.push(["Due Date", job.dueDate]);
  if (job.queueNotes) rows.push(["Queue Notes", job.queueNotes]);

  const attachmentCount = getJobAttachments(job).length;
  if (attachmentCount > 0) {
    rows.push(["Attachments", `${attachmentCount} attachment record(s) saved. See attachment section.`]);
  }

  if (form.customerTags) rows.push(["Customer Tags", form.customerTags]);
  if (form.customerNotes) rows.push(["Customer Notes", form.customerNotes]);

  if (form.printRuns?.length) {
    form.printRuns.forEach((run, index) => {
      rows.push([
        `Print Run ${index + 1}`,
        `${run.printerId || "Printer"} / ${run.nozzleSize || "Nozzle"} / ${
          run.materialId || "Material"
        } / ${run.materialGrams || 0}g / ${run.machineHours || 0} hr est.`,
      ]);
    });
  }

  if (job.jobAspects?.engraving || form.jobAspects?.engraving) {
    rows.push([
      "Laser Engraving",
      `${form.engravingModuleId || "Laser module"} / ${
        form.engravingMaterialId || "Material"
      } / ${form.engravingMaterialColor || "Finish"} / ${
        form.engravingMaterialUnits || 1
      } unit(s).`,
    ]);
  }

  if (job.jobAspects?.vinyl || form.jobAspects?.vinyl) {
    rows.push([
      "Vinyl Cutting",
      `${form.vinylModuleId || "Cutter module"} service included as quoted.`,
    ]);
  }

  if (form.customerAddress) {
    rows.push(["Shipping / Delivery Address", form.customerAddress]);
  }

  rows.push(...buildShippingRows(job));

  if (form.notes) {
    rows.push(["Project Notes", form.notes]);
  }

  return rows;
}

function buildInternalChecklistRows(job) {
  const form = job.formData || job.quoteSnapshot?.formData || {};
  const attachmentCount = getJobAttachments(job).length;

  const rows = [
    ["☐", "Confirm customer info and scope"],
    ["☐", "Confirm priority and due date"],
    ["☐", "Confirm quote revision/source if this is a revised quote"],
    ["☐", "Confirm required files/designs/references are available"],
    ["☐", "Confirm material/color/module selections"],
  ];

  if (attachmentCount > 0) {
    rows.push(["☐", `Review ${attachmentCount} saved attachment record(s)`]);
  }

  if (job.jobAspects?.cad || form.jobAspects?.cad) {
    rows.push(["☐", "CAD complete / design approved"]);
  }

  if (job.jobAspects?.printing || form.jobAspects?.printing) {
    rows.push(["☐", "Slicer settings checked"]);
    rows.push(["☐", "Print started"]);
    rows.push(["☐", "Print completed"]);
    rows.push(["☐", "Supports removed / cleanup completed"]);
  }

  if (job.jobAspects?.engraving || form.jobAspects?.engraving) {
    rows.push(["☐", "Laser file checked"]);
    rows.push(["☐", "Material aligned"]);
    rows.push(["☐", "Engraving test / focus checked"]);
    rows.push(["☐", "Engraving completed"]);
  }

  if (job.jobAspects?.vinyl || form.jobAspects?.vinyl) {
    rows.push(["☐", "Cut file checked"]);
    rows.push(["☐", "Vinyl cut completed"]);
    rows.push(["☐", "Weeding / transfer completed"]);
  }

  if (getShippingEstimate(job)) {
    rows.push(["☐", "Package dimensions and weight confirmed"]);
    rows.push(["☐", "Shipping label purchased"]);
    rows.push(["☐", "Tracking number saved / sent"]);
  }

  rows.push(["☐", "Final quality check"]);
  rows.push(["☐", "Photos taken if needed"]);
  rows.push(["☐", "Customer notified"]);
  rows.push(["☐", "Pickup / shipping completed"]);

  return rows;
}

function addShippingSectionIfNeeded(doc, record, y, documentTitle, numberText) {
  const shippingRows = buildShippingRows(record);

  if (shippingRows.length === 0) return y;

  y = addSectionTitle(doc, "Shipping / Delivery", y, documentTitle, numberText);

  return addTable(
    doc,
    {
      startY: y,
      head: [["Item", "Details"]],
      body: shippingRows,
      theme: "grid",
      headStyles: {
        fillColor: RED,
        textColor: [255, 255, 255],
      },
      styles: {
        fontSize: 8,
        cellPadding: 3,
        overflow: "linebreak",
      },
      columnStyles: {
        0: { cellWidth: 45, fontStyle: "bold" },
        1: { cellWidth: 137 },
      },
    },
    documentTitle,
    numberText
  );
}

function addRevisionSectionIfNeeded(doc, record, y, documentTitle, numberText) {
  const revisionRows = getRevisionRows(record);
  const revisionSummary = getRevisionSummary(record);

  if (revisionRows.length === 0 && !revisionSummary) return y;

  y = addSectionTitle(doc, "Quote Revision / Source", y, documentTitle, numberText);

  const body = [...revisionRows];

  if (revisionSummary) {
    body.push(["Summary", revisionSummary]);
  }

  return addTable(
    doc,
    {
      startY: y,
      head: [["Item", "Details"]],
      body,
      theme: "grid",
      headStyles: {
        fillColor: RED,
        textColor: [255, 255, 255],
      },
      styles: {
        fontSize: 8,
        cellPadding: 3,
        overflow: "linebreak",
      },
      columnStyles: {
        0: { cellWidth: 45, fontStyle: "bold" },
        1: { cellWidth: 137 },
      },
    },
    documentTitle,
    numberText
  );
}

export function exportQuotePdf(quote) {
  const doc = new jsPDF();

  const revisionNumber = Number(quote.revisionNumber || 0);
  const revisionSuffix = revisionNumber > 0 ? ` / Revision ${revisionNumber}` : "";
  const documentTitle = "QUOTE";
  const numberText = `Quote Number: ${quote.quoteNumber || "N/A"}${revisionSuffix}`;

  let y = addHeader(doc, documentTitle, numberText, "CUSTOMER QUOTE");

  y = addAmountDueBox(
    doc,
    {
      label: "ESTIMATED PROJECT TOTAL",
      amount: quote.finalTotal,
      subLabel: "Custom work estimate. Final pricing may change if scope or materials change.",
    },
    y,
    documentTitle,
    numberText
  );

  y = addInfoBlock(doc, quote, y, documentTitle, numberText);
  y = addRevisionSectionIfNeeded(doc, quote, y, documentTitle, numberText);

  y = addSectionTitle(doc, "Customer Quote Summary", y, documentTitle, numberText);
  y = addTotalsBox(doc, getServiceRows(quote, "customer"), y, documentTitle, numberText);

  y = addSectionTitle(doc, "Deposit / Payment Estimate", y, documentTitle, numberText);

  y = addTotalsBox(
    doc,
    [
      ["Suggested Deposit to Start", money(quote.depositAmount)],
      ["Estimated Remaining Balance", money(quote.remainingBalance)],
      ["Estimated Project Total", money(quote.finalTotal)],
    ],
    y,
    documentTitle,
    numberText
  );

  y = addShippingSectionIfNeeded(doc, quote, y, documentTitle, numberText);

  const form = quote.formData || {};

  y = addSectionTitle(doc, "Project Notes", y, documentTitle, numberText);

  const notes = [
    getRevisionSummary(quote) ? `Revision Info: ${getRevisionSummary(quote)}` : "",
    form.customerNotes ? `Customer Notes: ${form.customerNotes}` : "",
    form.notes ? `Project Notes: ${form.notes}` : "",
  ]
    .filter(Boolean)
    .join("\n\n");

  y = addWrappedText(doc, notes || form.notes, y, documentTitle, numberText);

  y = addSectionTitle(doc, "Terms", y, documentTitle, numberText);

  const terms = [
    "This quote is an estimate based on the project details available at the time it was created.",
    "Final pricing may change if project scope, material choice, quantity, design requirements, shipping, or supply costs change.",
    "If this quote is marked as a revision, it supersedes prior draft versions only when accepted by the customer and Overkill Solutions.",
    "Shipping estimates are based on available dimensions, package weight, carrier/service selection, and manual carrier quotes entered into the system.",
    "Custom work may require a deposit before production begins.",
    "Accepted payment methods: Cash, Venmo, Cash App, PayPal, and Zelle.",
  ].join("\n");

  y = addWrappedText(doc, terms, y, documentTitle, numberText);
  y = addSignatureSection(doc, y, documentTitle, numberText);

  addEmbeddedData(doc, {
    app: "overkill-solutions-app",
    version: 1,
    kind: "quote",
    exportedAt: new Date().toISOString(),
    record: quote,
  });

  const revisionFilePart = revisionNumber > 0 ? `-rev-${revisionNumber}` : "";

  doc.save(
    `${safeFileName(quote.quoteNumber)}${revisionFilePart}-${safeFileName(
      quote.customerName
    )}-quote.pdf`
  );
}

export function exportInvoicePdf(job) {
  const doc = new jsPDF();

  const invoiceNumber = getInvoiceNumber(job);
  const revisionNumber = Number(job.revisionNumber || job.quoteSnapshot?.revisionNumber || 0);
  const revisionSuffix = revisionNumber > 0 ? ` / Quote Rev ${revisionNumber}` : "";
  const documentTitle = "INVOICE";
  const numberText = `Invoice Number: ${invoiceNumber}${revisionSuffix}`;

  const { totalPaid, remaining, status } = getPaymentTotals(job);

  let y = addHeader(doc, documentTitle, numberText, "CUSTOMER INVOICE");

  y = addAmountDueBox(
    doc,
    {
      label: remaining > 0 ? "AMOUNT DUE" : "BALANCE PAID",
      amount: remaining,
      subLabel: `Payment status: ${status}`,
      paid: totalPaid,
      total: job.finalTotal,
    },
    y,
    documentTitle,
    numberText
  );

  y = addInfoBlock(
    doc,
    job,
    y,
    documentTitle,
    numberText,
    [
      ["Job Number", job.jobNumber || "N/A"],
      ["Quote Number", job.quoteNumber || "N/A"],
      ["Payment Status", status],
    ]
  );

  y = addRevisionSectionIfNeeded(doc, job, y, documentTitle, numberText);

  y = addSectionTitle(doc, "Invoice Summary", y, documentTitle, numberText);

  y = addTotalsBox(
    doc,
    [
      ["Final Job Total", money(job.finalTotal)],
      ["Paid So Far", money(totalPaid)],
      ["Remaining Balance", money(remaining)],
    ],
    y,
    documentTitle,
    numberText
  );

  y = addSectionTitle(doc, "Customer Service Breakdown", y, documentTitle, numberText);
  y = addTotalsBox(doc, getServiceRows(job, "customer"), y, documentTitle, numberText);

  y = addShippingSectionIfNeeded(doc, job, y, documentTitle, numberText);

  const productionRows = buildProductionSummary(job);

  if (productionRows.length > 0) {
    y = addSectionTitle(doc, "Project / Scope Details", y, documentTitle, numberText);

    y = addTable(
      doc,
      {
        startY: y,
        head: [["Item", "Details"]],
        body: productionRows,
        theme: "grid",
        headStyles: {
          fillColor: RED,
          textColor: [255, 255, 255],
        },
        alternateRowStyles: {
          fillColor: [250, 250, 250],
        },
        styles: {
          fontSize: 8,
          cellPadding: 3.3,
          overflow: "linebreak",
        },
        columnStyles: {
          0: { cellWidth: 45, fontStyle: "bold" },
          1: { cellWidth: 137 },
        },
      },
      documentTitle,
      numberText
    );
  }

  y = addSectionTitle(doc, "Payment History", y, documentTitle, numberText);

  y = addTable(
    doc,
    {
      startY: y,
      head: [["Date", "Time", "Type", "Method", "Amount", "Notes"]],
      body:
        job.paymentEvents?.length > 0
          ? job.paymentEvents.map((payment) => [
              payment.date || "",
              payment.time || "",
              payment.type || "",
              payment.method || "",
              money(payment.amount),
              payment.notes || "",
            ])
          : [["No payments recorded", "", "", "", "", ""]],
      theme: "grid",
      headStyles: {
        fillColor: RED,
        textColor: [255, 255, 255],
      },
      alternateRowStyles: {
        fillColor: [250, 250, 250],
      },
      styles: {
        fontSize: 8,
        cellPadding: 3,
        overflow: "linebreak",
      },
    },
    documentTitle,
    numberText
  );

  addSignatureSection(doc, y, documentTitle, numberText);

  addEmbeddedData(doc, {
    app: "overkill-solutions-app",
    version: 1,
    kind: "job",
    exportedAt: new Date().toISOString(),
    record: job,
  });

  const revisionFilePart = revisionNumber > 0 ? `-quote-rev-${revisionNumber}` : "";

  doc.save(
    `${safeFileName(invoiceNumber)}${revisionFilePart}-${safeFileName(
      job.customerName
    )}-invoice.pdf`
  );
}

export function exportProductionSheetPdf(job) {
  const doc = new jsPDF();

  const revisionNumber = Number(job.revisionNumber || job.quoteSnapshot?.revisionNumber || 0);
  const revisionSuffix = revisionNumber > 0 ? ` / Quote Rev ${revisionNumber}` : "";

  const documentTitle = "PRODUCTION SHEET";
  const numberText = `Job Number: ${job.jobNumber || "N/A"}${revisionSuffix}`;
  const form = job.formData || job.quoteSnapshot?.formData || {};
  const invoiceNumber = getInvoiceNumber(job);

  let y = addHeader(doc, documentTitle, numberText, "INTERNAL COPY");

  y = addInfoBlock(
    doc,
    job,
    y,
    documentTitle,
    numberText,
    [
      ["Invoice Number", invoiceNumber],
      ["Quote Number", job.quoteNumber || "N/A"],
      ["Job Status", job.status || "Approved"],
      ["Internal Use", "Not a customer invoice"],
    ]
  );

  y = addRevisionSectionIfNeeded(doc, job, y, documentTitle, numberText);

  y = addSectionTitle(doc, "Production Scope", y, documentTitle, numberText);

  const scopeRows = buildProductionSummary(job);

  y = addTable(
    doc,
    {
      startY: y,
      head: [["Item", "Details"]],
      body: scopeRows.length > 0
        ? scopeRows
        : [["General", "No detailed production scope saved."]],
      theme: "grid",
      headStyles: {
        fillColor: RED,
        textColor: [255, 255, 255],
      },
      alternateRowStyles: {
        fillColor: [250, 250, 250],
      },
      styles: {
        fontSize: 8,
        cellPadding: 3,
        overflow: "linebreak",
      },
      columnStyles: {
        0: { cellWidth: 45, fontStyle: "bold" },
        1: { cellWidth: 137 },
      },
    },
    documentTitle,
    numberText
  );

  y = addAttachmentsSectionIfNeeded(doc, job, y, documentTitle, numberText);

  if (form.printRuns?.length > 0) {
    y = addSectionTitle(doc, "Print Run Details", y, documentTitle, numberText);

    y = addTable(
      doc,
      {
        startY: y,
        head: [["Run", "Printer", "Nozzle", "Material", "Grams", "Hours", "Rate"]],
        body: form.printRuns.map((run, index) => [
          `Run ${index + 1}`,
          run.printerId || "",
          run.nozzleSize || "",
          run.materialId || "",
          `${run.materialGrams || 0}g`,
          `${run.machineHours || 0}`,
          money(run.machineRate || 0),
        ]),
        theme: "grid",
        headStyles: {
          fillColor: RED,
          textColor: [255, 255, 255],
        },
        alternateRowStyles: {
          fillColor: [250, 250, 250],
        },
        styles: {
          fontSize: 8,
          cellPadding: 3,
          overflow: "linebreak",
        },
      },
      documentTitle,
      numberText
    );
  }

  y = addSectionTitle(doc, "Internal Cost Breakdown", y, documentTitle, numberText);
  y = addTotalsBox(doc, getServiceRows(job, "internal"), y, documentTitle, numberText);

  y = addShippingSectionIfNeeded(doc, job, y, documentTitle, numberText);

  y = addSectionTitle(doc, "Production Checklist", y, documentTitle, numberText);

  y = addTable(
    doc,
    {
      startY: y,
      head: [["", "Task"]],
      body: buildInternalChecklistRows(job),
      theme: "grid",
      headStyles: {
        fillColor: RED,
        textColor: [255, 255, 255],
      },
      alternateRowStyles: {
        fillColor: [250, 250, 250],
      },
      styles: {
        fontSize: 9,
        cellPadding: 3,
        overflow: "linebreak",
      },
      columnStyles: {
        0: { cellWidth: 12, halign: "center" },
        1: { cellWidth: 170 },
      },
    },
    documentTitle,
    numberText
  );

  y = addSectionTitle(doc, "Internal Notes", y, documentTitle, numberText);
  y = addWrappedText(
    doc,
    [
      getRevisionSummary(job) ? `Revision Info: ${getRevisionSummary(job)}` : "",
      form.customerNotes ? `Customer Notes: ${form.customerNotes}` : "",
      form.customerTags ? `Customer Tags: ${form.customerTags}` : "",
      form.notes ? `Quote Notes: ${form.notes}` : "",
      job.queueNotes ? `Queue Notes: ${job.queueNotes}` : "",
      job.actuals?.notes ? `Actual Notes: ${job.actuals.notes}` : "",
      job.payments?.paymentNotes ? `Payment Notes: ${job.payments.paymentNotes}` : "",
      getShippingEstimate(job)?.notes
        ? `Shipping Notes: ${getShippingEstimate(job).notes}`
        : "",
    ]
      .filter(Boolean)
      .join("\n\n") || "No internal notes saved.",
    y,
    documentTitle,
    numberText
  );

  addInternalSignoffSection(doc, y, documentTitle, numberText);

  addEmbeddedData(doc, {
    app: "overkill-solutions-app",
    version: 1,
    kind: "production-sheet",
    exportedAt: new Date().toISOString(),
    record: job,
  });

  const revisionFilePart = revisionNumber > 0 ? `-quote-rev-${revisionNumber}` : "";

  doc.save(
    `${safeFileName(job.jobNumber)}${revisionFilePart}-${safeFileName(
      job.customerName
    )}-production-sheet.pdf`
  );
}