import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import overkillLogo from "../assets/logos/overkill_main.png";
import overkillMark from "../assets/logos/overkill_mark.png";

const RED = [214, 40, 40];
const DARK = [18, 18, 18];
const GRAY = [105, 105, 105];
const LIGHT = [235, 235, 235];

const PAGE = {
  left: 14,
  right: 196,
  bottom: 272,
};

const START_MARKER = "OVERKILL_DATA_START";
const END_MARKER = "OVERKILL_DATA_END";

function money(value) {
  return Number(value || 0).toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
  });
}

function num(value) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : 0;
}

function safeFileName(value) {
  return String(value || "document")
    .replace(/[^a-z0-9-_ ]/gi, "")
    .replace(/\s+/g, "-")
    .toLowerCase();
}

function encodeBase64Unicode(value) {
  const json = JSON.stringify(value);
  const bytes = new TextEncoder().encode(json);

  let binary = "";
  const chunkSize = 0x8000;

  for (let index = 0; index < bytes.length; index += chunkSize) {
    const chunk = bytes.subarray(index, index + chunkSize);
    binary += String.fromCharCode(...chunk);
  }

  return btoa(binary);
}

function addEmbeddedData(doc, payload) {
  const encoded = encodeBase64Unicode(payload);
  const fullText = `${START_MARKER}${encoded}${END_MARKER}`;
  const chunks = fullText.match(/.{1,90}/g) || [];

  const originalPage = doc.internal.getCurrentPageInfo().pageNumber;

  doc.addPage();
  doc.setFont("helvetica", "normal");
  doc.setFontSize(1);
  doc.setTextColor(255, 255, 255);

  let y = 4;

  chunks.forEach((chunk) => {
    if (y > 285) {
      doc.addPage();
      doc.setFont("helvetica", "normal");
      doc.setFontSize(1);
      doc.setTextColor(255, 255, 255);
      y = 4;
    }

    doc.text(chunk, 2, y);
    y += 2;
  });

  doc.setPage(originalPage);
}

function buildAspectList(jobAspects = {}) {
  const labels = [];

  if (jobAspects.cad) labels.push("CAD Modeling");
  if (jobAspects.printing) labels.push("3D Printing");
  if (jobAspects.engraving) labels.push("Laser Engraving");
  if (jobAspects.vinyl) labels.push("Vinyl Cutting");
  if (jobAspects.custom) labels.push("Custom Fabrication");

  return labels.length ? labels.join(", ") : "Custom Work";
}

function getInvoiceNumber(job) {
  if (job.invoiceNumber) return job.invoiceNumber;
  if (job.recordNumber) return `INV-${job.recordNumber}`;
  if (job.jobNumber) return job.jobNumber.replace("J-", "INV-");
  return "INV-DRAFT";
}

function addFooter(doc) {
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.setDrawColor(...LIGHT);
  doc.line(PAGE.left, pageHeight - 18, PAGE.right, pageHeight - 18);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);

  doc.text("Overkill Solutions", PAGE.left, pageHeight - 11);

  doc.text(
    "Generated by Overkill Solutions Internal Production System",
    PAGE.right,
    pageHeight - 11,
    { align: "right" }
  );
}

function addHeader(doc, title, numberText) {
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(...DARK);
  doc.rect(0, 0, pageWidth, 42, "F");

  doc.setFillColor(...RED);
  doc.rect(0, 40, pageWidth, 3, "F");

  try {
    doc.addImage(overkillLogo, "PNG", PAGE.left, 8, 62, 20);
  } catch {
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text("OVERKILL SOLUTIONS", PAGE.left, 20);
  }

  try {
    doc.addImage(overkillMark, "PNG", 180, 8, 16, 16);
  } catch {
    // Optional mark fallback.
  }

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text(title, PAGE.left, 58);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...GRAY);
  doc.text(numberText, PAGE.left, 65);

  addFooter(doc);

  return 74;
}

function addContinuationHeader(doc, title, numberText) {
  doc.addPage();

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...RED);
  doc.text(`OVERKILL SOLUTIONS — ${title}`, PAGE.left, 14);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.text(numberText, PAGE.right, 14, { align: "right" });

  doc.setDrawColor(...LIGHT);
  doc.line(PAGE.left, 18, PAGE.right, 18);

  addFooter(doc);

  return 28;
}

function ensureSpace(doc, y, neededHeight, title, numberText) {
  if (y + neededHeight <= PAGE.bottom) return y;
  return addContinuationHeader(doc, title, numberText);
}

function addSectionTitle(doc, titleText, y, documentTitle, numberText) {
  y = ensureSpace(doc, y, 18, documentTitle, numberText);

  doc.setFont("helvetica", "bold");
  doc.setTextColor(...RED);
  doc.setFontSize(13);
  doc.text(titleText, PAGE.left, y);

  doc.setDrawColor(...LIGHT);
  doc.line(PAGE.left, y + 3, PAGE.right, y + 3);

  return y + 10;
}

function addWrappedText(doc, text, y, documentTitle, numberText) {
  doc.setFont("helvetica", "normal");
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(9);

  const lines = doc.splitTextToSize(text || "None provided.", 182);
  const lineHeight = 5;

  y = ensureSpace(doc, y, lines.length * lineHeight + 8, documentTitle, numberText);

  let currentY = y;

  lines.forEach((line) => {
    if (currentY + lineHeight > PAGE.bottom) {
      currentY = addContinuationHeader(doc, documentTitle, numberText);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(40, 40, 40);
      doc.setFontSize(9);
    }

    doc.text(line, PAGE.left, currentY);
    currentY += lineHeight;
  });

  return currentY + 8;
}

function buildContactRows(record) {
  const rows = [
    ["Customer", record.customerName || "Unnamed Customer"],
  ];

  if (record.customerPhone || record.formData?.customerPhone) {
    rows.push(["Phone", record.customerPhone || record.formData?.customerPhone || ""]);
  }

  if (record.customerEmail || record.formData?.customerEmail) {
    rows.push(["Email", record.customerEmail || record.formData?.customerEmail || ""]);
  }

  if (record.customerAddress || record.formData?.customerAddress) {
    rows.push(["Address", record.customerAddress || record.formData?.customerAddress || ""]);
  }

  return rows;
}

function addInfoBlock(doc, record, startY, title, numberText, extraRows = []) {
  const date = new Date(
    record.createdAt || record.approvedAt || Date.now()
  ).toLocaleDateString();

  const rows = [
    ...buildContactRows(record),
    ["Project", record.jobName || "Untitled Project"],
    ["Date", date],
    ["Services", buildAspectList(record.jobAspects)],
    ...extraRows,
  ];

  startY = ensureSpace(doc, startY, rows.length * 8 + 12, title, numberText);

  autoTable(doc, {
    startY,
    body: rows,
    theme: "plain",
    styles: {
      fontSize: 10,
      cellPadding: 2,
      overflow: "linebreak",
    },
    columnStyles: {
      0: {
        fontStyle: "bold",
        textColor: RED,
        cellWidth: 38,
      },
      1: {
        textColor: [30, 30, 30],
        cellWidth: 144,
      },
    },
    margin: {
      left: PAGE.left,
      right: PAGE.left,
    },
  });

  return doc.lastAutoTable.finalY + 8;
}

function addTotalsBox(doc, rows, startY, documentTitle, numberText) {
  if (!rows.length) return startY;

  startY = ensureSpace(doc, startY, rows.length * 10 + 18, documentTitle, numberText);

  autoTable(doc, {
    startY,
    body: rows,
    theme: "grid",
    margin: {
      left: PAGE.left,
      right: PAGE.left,
    },
    pageBreak: "auto",
    rowPageBreak: "avoid",
    styles: {
      fontSize: 10,
      cellPadding: 4,
      lineColor: [220, 220, 220],
      lineWidth: 0.2,
      overflow: "linebreak",
    },
    columnStyles: {
      0: {
        fontStyle: "bold",
        textColor: [60, 60, 60],
        cellWidth: 120,
      },
      1: {
        halign: "right",
        fontStyle: "bold",
      },
    },
    didParseCell(data) {
      if (data.row.index === rows.length - 1) {
        data.cell.styles.fillColor = RED;
        data.cell.styles.textColor = [255, 255, 255];
        data.cell.styles.fontStyle = "bold";
      }
    },
    didDrawPage() {
      addFooter(doc);
    },
  });

  return doc.lastAutoTable.finalY + 10;
}

function addTable(doc, options, documentTitle, numberText) {
  const startY = ensureSpace(doc, options.startY, 40, documentTitle, numberText);

  autoTable(doc, {
    ...options,
    startY,
    margin: {
      left: PAGE.left,
      right: PAGE.left,
    },
    pageBreak: "auto",
    rowPageBreak: "avoid",
    didDrawPage() {
      addFooter(doc);
    },
  });

  return doc.lastAutoTable.finalY + 10;
}

function applyBufferToQuoteRows(totals, form, record) {
  const bufferMultiplier = 1 + num(totals.appliedBufferPercent) / 100;
  const buffered = (value) => money(num(value) * bufferMultiplier);

  const finishingOther =
    num(form.finishingFee) + num(form.shippingFee) + num(form.complexityFee);

  return [
    ["CAD Design", buffered(totals.cadCost)],
    ["3D Print Material", buffered(totals.printMaterialCost)],
    ["3D Print Machine Time", buffered(totals.machineCost)],
    ["3D Print Setup", buffered(totals.setupFee)],
    ["Engraving Material", buffered(totals.engravingMaterialCost)],
    ["Engraving Service", buffered(totals.engravingCost)],
    ["Vinyl Material", buffered(totals.vinylMaterialCost)],
    ["Vinyl Service", buffered(totals.vinylCost)],
    ["Project Integration", buffered(totals.integrationCost)],
    ["Custom Fabrication", buffered(totals.customCost)],
    ["Extra Labor", buffered(totals.extraLaborCost)],
    ["Finishing / Delivery / Other", buffered(finishingOther)],
    ["Discount", `-${money(form.discount)}`],
    ["Tax", money(totals.tax)],
    ["Final Total", money(record.finalTotal)],
  ].filter((row) => row[1] !== "$0.00" && row[1] !== "-$0.00");
}

function getServiceRows(record) {
  const totals = record.totals || record.quoteSnapshot?.totals || {};
  const form = record.formData || record.quoteSnapshot?.formData || {};

  return applyBufferToQuoteRows(totals, form, record);
}

function getPaymentTotals(job) {
  const payments = job.paymentEvents || [];

  const totalPaid = payments.reduce((sum, payment) => {
    if (payment.type === "Refund") return sum - num(payment.amount);
    return sum + num(payment.amount);
  }, 0);

  const remaining = Math.max(0, num(job.finalTotal) - totalPaid);

  let status = "Unpaid";
  if (totalPaid > 0 && totalPaid < num(job.finalTotal)) status = "Partially Paid";
  if (totalPaid >= num(job.finalTotal)) status = totalPaid > num(job.finalTotal) ? "Overpaid" : "Paid in Full";

  return { totalPaid, remaining, status };
}

function buildProductionSummary(job) {
  const form = job.formData || job.quoteSnapshot?.formData || {};
  const rows = [];

  if (form.printRuns?.length) {
    form.printRuns.forEach((run, index) => {
      rows.push([
        `Print Run ${index + 1}`,
        `${run.printerId || "Printer"} / ${run.nozzleSize || "Nozzle"}mm / ${run.materialId || "Material"} / ${run.materialGrams || 0}g / ${run.machineHours || 0} hr est.`,
      ]);
    });
  }

  if (job.jobAspects?.engraving) {
    rows.push(["Laser Engraving", "H2S laser engraving service included as quoted."]);
  }

  if (job.jobAspects?.vinyl) {
    rows.push(["Vinyl Cutting", "H2S cutting/vinyl service included as quoted."]);
  }

  if (form.customerAddress) {
    rows.push(["Shipping / Delivery Address", form.customerAddress]);
  }

  if (form.notes) {
    rows.push(["Project Notes", form.notes]);
  }

  return rows;
}

export function exportQuotePdf(quote) {
  const doc = new jsPDF();

  const documentTitle = "QUOTE";
  const numberText = `Quote Number: ${quote.quoteNumber || "N/A"}`;

  let y = addHeader(doc, documentTitle, numberText);

  y = addInfoBlock(doc, quote, y, documentTitle, numberText);

  y = addSectionTitle(doc, "Quote Summary", y, documentTitle, numberText);

  y = addTotalsBox(doc, getServiceRows(quote), y, documentTitle, numberText);

  y = addSectionTitle(doc, "Payment Estimate", y, documentTitle, numberText);

  y = addTotalsBox(
    doc,
    [
      ["Suggested Deposit", money(quote.depositAmount)],
      ["Remaining Balance", money(quote.remainingBalance)],
      ["Total", money(quote.finalTotal)],
    ],
    y,
    documentTitle,
    numberText
  );

  const form = quote.formData || {};

  y = addSectionTitle(doc, "Project Notes", y, documentTitle, numberText);
  y = addWrappedText(doc, form.notes, y, documentTitle, numberText);

  y = addSectionTitle(doc, "Terms", y, documentTitle, numberText);

  const terms = [
    "This quote is an estimate based on the project details available at the time it was created.",
    "Final pricing may change if project scope, material choice, quantity, design requirements, shipping, or supply costs change.",
    "Custom work may require a deposit before production begins.",
    "Accepted payment methods: Cash, Venmo, Cash App, PayPal, and Zelle.",
  ].join("\n");

  addWrappedText(doc, terms, y, documentTitle, numberText);

  addEmbeddedData(doc, {
    app: "overkill-solutions-app",
    version: 1,
    kind: "quote",
    exportedAt: new Date().toISOString(),
    record: quote,
  });

  doc.save(
    `${safeFileName(quote.quoteNumber)}-${safeFileName(
      quote.customerName
    )}-quote.pdf`
  );
}

export function exportInvoicePdf(job) {
  const doc = new jsPDF();

  const invoiceNumber = getInvoiceNumber(job);
  const documentTitle = "INVOICE";
  const numberText = `Invoice Number: ${invoiceNumber}`;

  const { totalPaid, remaining, status } = getPaymentTotals(job);

  let y = addHeader(doc, documentTitle, numberText);

  y = addInfoBlock(
    doc,
    job,
    y,
    documentTitle,
    numberText,
    [
      ["Job Number", job.jobNumber || "N/A"],
      ["Quote Number", job.quoteNumber || "N/A"],
      ["Payment Status", status],
    ]
  );

  y = addSectionTitle(doc, "Invoice Summary", y, documentTitle, numberText);

  y = addTotalsBox(
    doc,
    [
      ["Final Job Total", money(job.finalTotal)],
      ["Paid So Far", money(totalPaid)],
      ["Remaining Balance", money(remaining)],
    ],
    y,
    documentTitle,
    numberText
  );

  y = addSectionTitle(doc, "Service Breakdown", y, documentTitle, numberText);

  y = addTotalsBox(doc, getServiceRows(job), y, documentTitle, numberText);

  const productionRows = buildProductionSummary(job);

  if (productionRows.length > 0) {
    y = addSectionTitle(doc, "Production / Scope Details", y, documentTitle, numberText);

    y = addTable(
      doc,
      {
        startY: y,
        head: [["Item", "Details"]],
        body: productionRows,
        theme: "grid",
        headStyles: {
          fillColor: RED,
          textColor: [255, 255, 255],
        },
        styles: {
          fontSize: 8,
          cellPadding: 3,
          overflow: "linebreak",
        },
        columnStyles: {
          0: { cellWidth: 45, fontStyle: "bold" },
          1: { cellWidth: 137 },
        },
      },
      documentTitle,
      numberText
    );
  }

  y = addSectionTitle(doc, "Payment History", y, documentTitle, numberText);

  addTable(
    doc,
    {
      startY: y,
      head: [["Date", "Time", "Type", "Method", "Amount", "Notes"]],
      body:
        job.paymentEvents?.length > 0
          ? job.paymentEvents.map((payment) => [
              payment.date || "",
              payment.time || "",
              payment.type || "",
              payment.method || "",
              money(payment.amount),
              payment.notes || "",
            ])
          : [["No payments recorded", "", "", "", "", ""]],
      theme: "grid",
      headStyles: {
        fillColor: RED,
        textColor: [255, 255, 255],
      },
      styles: {
        fontSize: 8,
        cellPadding: 3,
        overflow: "linebreak",
      },
    },
    documentTitle,
    numberText
  );

  addEmbeddedData(doc, {
    app: "overkill-solutions-app",
    version: 1,
    kind: "job",
    exportedAt: new Date().toISOString(),
    record: job,
  });

  doc.save(
    `${safeFileName(invoiceNumber)}-${safeFileName(
      job.customerName
    )}-invoice.pdf`
  );
}