import jsPDF from "jspdf";

function money(value) {
  return Number(value || 0).toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
  });
}

function addLine(doc, label, value, y) {
  doc.setFont("helvetica", "normal");
  doc.text(label, 20, y);
  doc.setFont("helvetica", "bold");
  doc.text(value, 190, y, { align: "right" });
}

export function exportQuotePdf(quote) {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(214, 40, 40);
  doc.rect(0, 0, pageWidth, 18, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("OVERKILL SOLUTIONS", 20, 12);

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(22);
  doc.text("QUOTE", 20, 35);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Quote Number: ${quote.quoteNumber}`, 20, 45);
  doc.text(`Created: ${new Date(quote.createdAt).toLocaleDateString()}`, 20, 52);
  doc.text(`Status: ${quote.status}`, 20, 59);

  doc.setFont("helvetica", "bold");
  doc.text("Customer", 20, 75);
  doc.setFont("helvetica", "normal");
  doc.text(quote.customerName || "Customer not listed", 20, 83);

  doc.setFont("helvetica", "bold");
  doc.text("Job", 20, 98);
  doc.setFont("helvetica", "normal");
  doc.text(quote.jobName || "Untitled job", 20, 106);

  doc.setFont("helvetica", "bold");
  doc.text("Job Type(s)", 20, 121);

  const types = [];
  if (quote.jobAspects?.cad) types.push("CAD Modeling");
  if (quote.jobAspects?.printing) types.push("3D Printing");
  if (quote.jobAspects?.engraving) types.push("Laser Engraving");
  if (quote.jobAspects?.vinyl) types.push("Vinyl Cutting");
  if (quote.jobAspects?.custom) types.push("Custom Project");

  doc.setFont("helvetica", "normal");
  doc.text(types.length ? types.join(", ") : "Not specified", 20, 129);

  doc.setDrawColor(214, 40, 40);
  doc.line(20, 142, 190, 142);

  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text("Quote Summary", 20, 155);

  doc.setFontSize(11);
  let y = 168;

  addLine(doc, "Quoted Total", money(quote.finalTotal), y);
  y += 9;

  addLine(doc, "Suggested Deposit", money(quote.depositAmount), y);
  y += 9;

  addLine(doc, "Remaining Balance", money(quote.remainingBalance), y);
  y += 9;

  if (quote.totals) {
    addLine(doc, "Direct Subtotal", money(quote.totals.directSubtotal), y);
    y += 9;

    addLine(
      doc,
      `Quote Buffer (${quote.totals.appliedBufferPercent || 0}%)`,
      money(quote.totals.quoteBuffer),
      y
    );
    y += 9;
  }

  doc.setDrawColor(200, 200, 200);
  doc.line(20, y + 5, 190, y + 5);
  y += 20;

  doc.setFont("helvetica", "bold");
  doc.text("Notes / Terms", 20, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  const terms = [
    "This quote is an estimate based on the information available at the time it was created.",
    "Final price may change if the scope, material, design, quantity, or supply cost changes.",
    "Custom work may require a deposit before production begins.",
    "Payment methods currently accepted: Venmo, Cash, Cash App, PayPal, and Zelle.",
  ];

  terms.forEach((term) => {
    const lines = doc.splitTextToSize(term, 165);
    doc.text(lines, 20, y);
    y += lines.length * 6 + 3;
  });

  if (quote.formData?.notes) {
    y += 4;
    doc.setFont("helvetica", "bold");
    doc.text("Project Notes", 20, y);
    y += 8;

    doc.setFont("helvetica", "normal");
    const noteLines = doc.splitTextToSize(quote.formData.notes, 165);
    doc.text(noteLines, 20, y);
  }

  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(
    "Generated by Overkill Solutions Internal Production System",
    20,
    285
  );

  doc.save(`${quote.quoteNumber}-${quote.jobName || "quote"}.pdf`);
}